# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu9p-flgb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.cache/wt [current_project]
set_property parent.project_path /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/algo_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/regionizer_wrapper.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/infra_wrapper.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/level2_ram_buffers.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/level2_ram_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/level2_uram_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/level1_fifo_only_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/level1_fifo_only_buffers.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/regionizer_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/sim/algo_wrapper.vhd
}
read_vhdl -library xil_defaultlib {
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgokbM.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/ptsort_hwopt_ind.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgohbi.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_tkalgo.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_photons.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgodEe.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/simple_puppi_hw.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/p_lut_shift15_divmb6.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/spfph_mu2trk_linkste.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pack_out_s.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgobkb.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgofYi.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/dr2_plus_dpt_int_cap.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/em2calo_sumem.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/em2calo_sub.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/pick_closest_2.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/dr2_int_cap_12_s.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgolbW.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/pick_closest_1.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/dr2_int_cap_10_s.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgoeOg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_sumtk.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgoncg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_unpack_in.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/em2calo_link.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_drdptvals_cu.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgoibs.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_elealgo.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/pfalgo3_full.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/spfph_mu2trk_dptvals.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_link_drdpt.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_caloalgo.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgo3_full.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/simple_puppi_hw_pocq.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_emalgo.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_link.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgopcA.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_drvals_4195_s.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/dr2_int_cap_14_s.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgog8j.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/p_lut_shift15_divide.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/spfph_mualgo.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2calo_drdptvalsjbC.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/mp7wrapped_pfalgocud.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/pick_closest.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/tk2em_sumtk.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/algo/em2calo_drvals_262_s.vhd
}
read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full_walgo/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top infra_wrapper -part xcvu9p-flgb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef infra_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file infra_wrapper_utilization_synth.rpt -pb infra_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
