# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xci
# IP: The module: 'tmux_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xci
# IP: The module: 'tmux_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer/regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tmux_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
