# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.cache/wt [current_project]
set_property parent.project_path /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/algo_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_params_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_wrapper_layer1_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_wrapper_layer1_buffers.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_wrapper.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_wrapper_layer2_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/sim/tmux_wrapper_layer2_buffers.vhd
}
read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/tmux_clocks/tmux_clocks_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top algorithm_tb -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef algorithm_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file algorithm_tb_utilization_synth.rpt -pb algorithm_tb_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
