#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 08 22:21:14 CDT 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim regionizer_tb_behav -key {Behavioral:sim_1:Functional:regionizer_tb} -tclbatch regionizer_tb.tcl -view /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer_tb_behav.wcfg -log simulate.log
