# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xci
# IP: The module: 'raw_link_buffer_layer0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xci
# IP: The module: 'raw_link_buffer_layer0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/raw_link_buffer_layer0/raw_link_buffer_layer0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_link_buffer_layer0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
