# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram.xci
# IP: The module: 'physics_object_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'physics_object_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram.xci
# IP: The module: 'physics_object_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/tmux_regionizer/tmux_regionizer.srcs/sources_1/ip/physics_object_bram/physics_object_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'physics_object_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
