-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity em2calo_sub is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    calo_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_16_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_17_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_18_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_19_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_15_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_16_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_17_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_18_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_19_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_15_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_16_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_17_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_18_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_19_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_10_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_11_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_12_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_13_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_14_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_15_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_16_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_17_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_18_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_19_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwIsEM_read : IN STD_LOGIC;
    calo_1_hwIsEM_read : IN STD_LOGIC;
    calo_2_hwIsEM_read : IN STD_LOGIC;
    calo_3_hwIsEM_read : IN STD_LOGIC;
    calo_4_hwIsEM_read : IN STD_LOGIC;
    calo_5_hwIsEM_read : IN STD_LOGIC;
    calo_6_hwIsEM_read : IN STD_LOGIC;
    calo_7_hwIsEM_read : IN STD_LOGIC;
    calo_8_hwIsEM_read : IN STD_LOGIC;
    calo_9_hwIsEM_read : IN STD_LOGIC;
    calo_10_hwIsEM_read : IN STD_LOGIC;
    calo_11_hwIsEM_read : IN STD_LOGIC;
    calo_12_hwIsEM_read : IN STD_LOGIC;
    calo_13_hwIsEM_read : IN STD_LOGIC;
    calo_14_hwIsEM_read : IN STD_LOGIC;
    calo_15_hwIsEM_read : IN STD_LOGIC;
    calo_16_hwIsEM_read : IN STD_LOGIC;
    calo_17_hwIsEM_read : IN STD_LOGIC;
    calo_18_hwIsEM_read : IN STD_LOGIC;
    calo_19_hwIsEM_read : IN STD_LOGIC;
    sumem_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_16_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_18_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_19_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of em2calo_sub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ptsub_V_fu_984_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_reg_3264 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp3_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_reg_3269 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_1_fu_1060_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_1_reg_3276 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp18_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_reg_3281 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_2_fu_1136_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_2_reg_3288 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp33_fu_1206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_reg_3293 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_3_fu_1212_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_3_reg_3300 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp48_fu_1282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_reg_3305 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_4_fu_1288_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_4_reg_3312 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp63_fu_1358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_reg_3317 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_5_fu_1364_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_5_reg_3324 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp78_fu_1434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_reg_3329 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_6_fu_1440_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_6_reg_3336 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp93_fu_1510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp93_reg_3341 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_7_fu_1516_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_7_reg_3348 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp108_fu_1586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp108_reg_3353 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_8_fu_1592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_8_reg_3360 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp123_fu_1662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp123_reg_3365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_9_fu_1668_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_9_reg_3372 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp138_fu_1738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp138_reg_3377 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_s_fu_1744_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_s_reg_3384 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp153_fu_1814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp153_reg_3389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_10_fu_1820_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_10_reg_3396 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp168_fu_1890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp168_reg_3401 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_11_fu_1896_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_11_reg_3408 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp183_fu_1966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp183_reg_3413 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_12_fu_1972_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_12_reg_3420 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp198_fu_2042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp198_reg_3425 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_13_fu_2048_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_13_reg_3432 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp213_fu_2118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp213_reg_3437 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_14_fu_2124_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_14_reg_3444 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp228_fu_2194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp228_reg_3449 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_15_fu_2200_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_15_reg_3456 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp243_fu_2270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp243_reg_3461 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_16_fu_2276_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_16_reg_3468 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp258_fu_2346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp258_reg_3473 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_17_fu_2352_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_17_reg_3480 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp273_fu_2422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp273_reg_3485 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptsub_V_18_fu_2428_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_18_reg_3492 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp288_fu_2498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp288_reg_3497 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_calo_0_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_10_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_11_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_12_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_13_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_14_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_15_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_16_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_17_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_18_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_19_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_10_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_11_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_12_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_13_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_14_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_15_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_16_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_17_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_18_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_19_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_996_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_138_fu_1010_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_fu_1006_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_fu_1020_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_fu_990_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt56_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev56_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_1048_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_fu_1072_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_140_fu_1086_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_1_fu_1082_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt57_fu_1100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_1_fu_1096_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_fu_1066_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt58_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev58_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1124_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev57_fu_1106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_141_fu_1148_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_142_fu_1162_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_2_fu_1158_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt59_fu_1176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_2_fu_1172_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_fu_1142_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt60_fu_1188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev60_fu_1194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1200_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev59_fu_1182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_fu_1224_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_144_fu_1238_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_3_fu_1234_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt61_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_3_fu_1248_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_fu_1218_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt62_fu_1264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev62_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1276_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev61_fu_1258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_145_fu_1300_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_146_fu_1314_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_4_fu_1310_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt63_fu_1328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_4_fu_1324_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_fu_1294_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt64_fu_1340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev64_fu_1346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1352_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev63_fu_1334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_fu_1376_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_148_fu_1390_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_5_fu_1386_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt65_fu_1404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_5_fu_1400_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_fu_1370_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt66_fu_1416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev66_fu_1422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1428_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev65_fu_1410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_149_fu_1452_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_150_fu_1466_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_6_fu_1462_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt67_fu_1480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_6_fu_1476_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_fu_1446_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt68_fu_1492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev68_fu_1498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1504_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev67_fu_1486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_151_fu_1528_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_152_fu_1542_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_7_fu_1538_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt69_fu_1556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_7_fu_1552_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_fu_1522_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt70_fu_1568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev70_fu_1574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1580_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev69_fu_1562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_153_fu_1604_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_154_fu_1618_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_8_fu_1614_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt71_fu_1632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_8_fu_1628_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_fu_1598_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt72_fu_1644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev72_fu_1650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1656_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev71_fu_1638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_155_fu_1680_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_156_fu_1694_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_s_fu_1690_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt73_fu_1708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_9_fu_1704_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_fu_1674_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt74_fu_1720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev74_fu_1726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1732_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev73_fu_1714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_157_fu_1756_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_158_fu_1770_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_10_fu_1766_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt75_fu_1784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_s_fu_1780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_1_fu_1750_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt76_fu_1796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev76_fu_1802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp152_fu_1808_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp152_fu_1808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev75_fu_1790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_159_fu_1832_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_160_fu_1846_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_11_fu_1842_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt77_fu_1860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_10_fu_1856_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_10_fu_1826_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt78_fu_1872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev78_fu_1878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp167_fu_1884_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp167_fu_1884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev77_fu_1866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_161_fu_1908_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_162_fu_1922_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_12_fu_1918_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt79_fu_1936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_11_fu_1932_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_11_fu_1902_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt80_fu_1948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev80_fu_1954_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp182_fu_1960_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp182_fu_1960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev79_fu_1942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_163_fu_1984_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_164_fu_1998_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_13_fu_1994_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt81_fu_2012_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_12_fu_2008_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_12_fu_1978_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt82_fu_2024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev82_fu_2030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp197_fu_2036_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp197_fu_2036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev81_fu_2018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_165_fu_2060_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_166_fu_2074_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_14_fu_2070_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt83_fu_2088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_13_fu_2084_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_13_fu_2054_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt84_fu_2100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev84_fu_2106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp212_fu_2112_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp212_fu_2112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev83_fu_2094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_167_fu_2136_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_168_fu_2150_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_15_fu_2146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt85_fu_2164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_14_fu_2160_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_14_fu_2130_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt86_fu_2176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev86_fu_2182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp227_fu_2188_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp227_fu_2188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev85_fu_2170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_169_fu_2212_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_170_fu_2226_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_16_fu_2222_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt87_fu_2240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_15_fu_2236_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_15_fu_2206_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt88_fu_2252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev88_fu_2258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp242_fu_2264_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp242_fu_2264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev87_fu_2246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_fu_2288_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_172_fu_2302_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_17_fu_2298_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt89_fu_2316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_16_fu_2312_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_16_fu_2282_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt90_fu_2328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev90_fu_2334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp257_fu_2340_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp257_fu_2340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev89_fu_2322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_2364_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_174_fu_2378_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_18_fu_2374_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt91_fu_2392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_17_fu_2388_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_17_fu_2358_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt92_fu_2404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev92_fu_2410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp272_fu_2416_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp272_fu_2416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev91_fu_2398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_175_fu_2440_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_176_fu_2454_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_19_fu_2450_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt93_fu_2468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_18_fu_2464_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_18_fu_2434_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt94_fu_2480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev94_fu_2486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp287_fu_2492_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp287_fu_2492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev93_fu_2474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_out_0_hwPt_V_w_fu_2511_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_1_hwPt_V_w_fu_2531_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_2_hwPt_V_w_fu_2551_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_3_hwPt_V_w_fu_2571_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_4_hwPt_V_w_fu_2584_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_5_hwPt_V_w_fu_2604_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_6_hwPt_V_w_fu_2624_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_7_hwPt_V_w_fu_2644_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_8_hwPt_V_w_fu_2664_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_9_hwPt_V_w_fu_2684_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_10_hwPt_V_s_fu_2704_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_11_hwPt_V_s_fu_2724_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_12_hwPt_V_s_fu_2744_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_13_hwPt_V_s_fu_2764_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_14_hwPt_V_s_fu_2784_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_15_hwPt_V_s_fu_2804_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_16_hwPt_V_s_fu_2824_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_17_hwPt_V_s_fu_2844_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_18_hwPt_V_s_fu_2864_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_19_hwPt_V_s_fu_2884_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_0_hwEta_V_s_fu_2504_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwEta_V_s_fu_2524_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwEta_V_s_fu_2544_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwEta_V_s_fu_2564_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwEta_V_s_fu_2590_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwEta_V_s_fu_2610_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwEta_V_s_fu_2630_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwEta_V_s_fu_2650_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwEta_V_s_fu_2670_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwEta_V_s_fu_2690_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_10_hwEta_V_fu_2710_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_11_hwEta_V_fu_2730_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_12_hwEta_V_fu_2750_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_13_hwEta_V_fu_2770_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_14_hwEta_V_fu_2790_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_15_hwEta_V_fu_2810_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_16_hwEta_V_fu_2830_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_17_hwEta_V_fu_2850_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_18_hwEta_V_fu_2870_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_19_hwEta_V_fu_2890_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_0_hwPhi_V_s_fu_2517_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwPhi_V_s_fu_2537_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwPhi_V_s_fu_2557_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwPhi_V_s_fu_2577_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwPhi_V_s_fu_2597_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwPhi_V_s_fu_2617_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwPhi_V_s_fu_2637_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwPhi_V_s_fu_2657_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwPhi_V_s_fu_2677_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwPhi_V_s_fu_2697_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_10_hwPhi_V_fu_2717_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_11_hwPhi_V_fu_2737_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_12_hwPhi_V_fu_2757_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_13_hwPhi_V_fu_2777_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_14_hwPhi_V_fu_2797_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_15_hwPhi_V_fu_2817_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_16_hwPhi_V_fu_2837_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_17_hwPhi_V_fu_2857_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_18_hwPhi_V_fu_2877_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_19_hwPhi_V_fu_2897_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ap_port_reg_calo_0_hwEta_V_read <= calo_0_hwEta_V_read;
                ap_port_reg_calo_0_hwPhi_V_read <= calo_0_hwPhi_V_read;
                ap_port_reg_calo_10_hwEta_V_rea <= calo_10_hwEta_V_rea;
                ap_port_reg_calo_10_hwPhi_V_rea <= calo_10_hwPhi_V_rea;
                ap_port_reg_calo_11_hwEta_V_rea <= calo_11_hwEta_V_rea;
                ap_port_reg_calo_11_hwPhi_V_rea <= calo_11_hwPhi_V_rea;
                ap_port_reg_calo_12_hwEta_V_rea <= calo_12_hwEta_V_rea;
                ap_port_reg_calo_12_hwPhi_V_rea <= calo_12_hwPhi_V_rea;
                ap_port_reg_calo_13_hwEta_V_rea <= calo_13_hwEta_V_rea;
                ap_port_reg_calo_13_hwPhi_V_rea <= calo_13_hwPhi_V_rea;
                ap_port_reg_calo_14_hwEta_V_rea <= calo_14_hwEta_V_rea;
                ap_port_reg_calo_14_hwPhi_V_rea <= calo_14_hwPhi_V_rea;
                ap_port_reg_calo_15_hwEta_V_rea <= calo_15_hwEta_V_rea;
                ap_port_reg_calo_15_hwPhi_V_rea <= calo_15_hwPhi_V_rea;
                ap_port_reg_calo_16_hwEta_V_rea <= calo_16_hwEta_V_rea;
                ap_port_reg_calo_16_hwPhi_V_rea <= calo_16_hwPhi_V_rea;
                ap_port_reg_calo_17_hwEta_V_rea <= calo_17_hwEta_V_rea;
                ap_port_reg_calo_17_hwPhi_V_rea <= calo_17_hwPhi_V_rea;
                ap_port_reg_calo_18_hwEta_V_rea <= calo_18_hwEta_V_rea;
                ap_port_reg_calo_18_hwPhi_V_rea <= calo_18_hwPhi_V_rea;
                ap_port_reg_calo_19_hwEta_V_rea <= calo_19_hwEta_V_rea;
                ap_port_reg_calo_19_hwPhi_V_rea <= calo_19_hwPhi_V_rea;
                ap_port_reg_calo_1_hwEta_V_read <= calo_1_hwEta_V_read;
                ap_port_reg_calo_1_hwPhi_V_read <= calo_1_hwPhi_V_read;
                ap_port_reg_calo_2_hwEta_V_read <= calo_2_hwEta_V_read;
                ap_port_reg_calo_2_hwPhi_V_read <= calo_2_hwPhi_V_read;
                ap_port_reg_calo_3_hwEta_V_read <= calo_3_hwEta_V_read;
                ap_port_reg_calo_3_hwPhi_V_read <= calo_3_hwPhi_V_read;
                ap_port_reg_calo_4_hwEta_V_read <= calo_4_hwEta_V_read;
                ap_port_reg_calo_4_hwPhi_V_read <= calo_4_hwPhi_V_read;
                ap_port_reg_calo_5_hwEta_V_read <= calo_5_hwEta_V_read;
                ap_port_reg_calo_5_hwPhi_V_read <= calo_5_hwPhi_V_read;
                ap_port_reg_calo_6_hwEta_V_read <= calo_6_hwEta_V_read;
                ap_port_reg_calo_6_hwPhi_V_read <= calo_6_hwPhi_V_read;
                ap_port_reg_calo_7_hwEta_V_read <= calo_7_hwEta_V_read;
                ap_port_reg_calo_7_hwPhi_V_read <= calo_7_hwPhi_V_read;
                ap_port_reg_calo_8_hwEta_V_read <= calo_8_hwEta_V_read;
                ap_port_reg_calo_8_hwPhi_V_read <= calo_8_hwPhi_V_read;
                ap_port_reg_calo_9_hwEta_V_read <= calo_9_hwEta_V_read;
                ap_port_reg_calo_9_hwPhi_V_read <= calo_9_hwPhi_V_read;
                ptsub_V_10_reg_3396 <= ptsub_V_10_fu_1820_p2;
                ptsub_V_11_reg_3408 <= ptsub_V_11_fu_1896_p2;
                ptsub_V_12_reg_3420 <= ptsub_V_12_fu_1972_p2;
                ptsub_V_13_reg_3432 <= ptsub_V_13_fu_2048_p2;
                ptsub_V_14_reg_3444 <= ptsub_V_14_fu_2124_p2;
                ptsub_V_15_reg_3456 <= ptsub_V_15_fu_2200_p2;
                ptsub_V_16_reg_3468 <= ptsub_V_16_fu_2276_p2;
                ptsub_V_17_reg_3480 <= ptsub_V_17_fu_2352_p2;
                ptsub_V_18_reg_3492 <= ptsub_V_18_fu_2428_p2;
                ptsub_V_1_reg_3276 <= ptsub_V_1_fu_1060_p2;
                ptsub_V_2_reg_3288 <= ptsub_V_2_fu_1136_p2;
                ptsub_V_3_reg_3300 <= ptsub_V_3_fu_1212_p2;
                ptsub_V_4_reg_3312 <= ptsub_V_4_fu_1288_p2;
                ptsub_V_5_reg_3324 <= ptsub_V_5_fu_1364_p2;
                ptsub_V_6_reg_3336 <= ptsub_V_6_fu_1440_p2;
                ptsub_V_7_reg_3348 <= ptsub_V_7_fu_1516_p2;
                ptsub_V_8_reg_3360 <= ptsub_V_8_fu_1592_p2;
                ptsub_V_9_reg_3372 <= ptsub_V_9_fu_1668_p2;
                ptsub_V_reg_3264 <= ptsub_V_fu_984_p2;
                ptsub_V_s_reg_3384 <= ptsub_V_s_fu_1744_p2;
                sel_tmp108_reg_3353 <= sel_tmp108_fu_1586_p2;
                sel_tmp123_reg_3365 <= sel_tmp123_fu_1662_p2;
                sel_tmp138_reg_3377 <= sel_tmp138_fu_1738_p2;
                sel_tmp153_reg_3389 <= sel_tmp153_fu_1814_p2;
                sel_tmp168_reg_3401 <= sel_tmp168_fu_1890_p2;
                sel_tmp183_reg_3413 <= sel_tmp183_fu_1966_p2;
                sel_tmp18_reg_3281 <= sel_tmp18_fu_1130_p2;
                sel_tmp198_reg_3425 <= sel_tmp198_fu_2042_p2;
                sel_tmp213_reg_3437 <= sel_tmp213_fu_2118_p2;
                sel_tmp228_reg_3449 <= sel_tmp228_fu_2194_p2;
                sel_tmp243_reg_3461 <= sel_tmp243_fu_2270_p2;
                sel_tmp258_reg_3473 <= sel_tmp258_fu_2346_p2;
                sel_tmp273_reg_3485 <= sel_tmp273_fu_2422_p2;
                sel_tmp288_reg_3497 <= sel_tmp288_fu_2498_p2;
                sel_tmp33_reg_3293 <= sel_tmp33_fu_1206_p2;
                sel_tmp3_reg_3269 <= sel_tmp3_fu_1054_p2;
                sel_tmp48_reg_3305 <= sel_tmp48_fu_1282_p2;
                sel_tmp63_reg_3317 <= sel_tmp63_fu_1358_p2;
                sel_tmp78_reg_3329 <= sel_tmp78_fu_1434_p2;
                sel_tmp93_reg_3341 <= sel_tmp93_fu_1510_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= calo_out_0_hwPt_V_w_fu_2511_p3;
    ap_return_1 <= calo_out_1_hwPt_V_w_fu_2531_p3;
    ap_return_10 <= calo_out_10_hwPt_V_s_fu_2704_p3;
    ap_return_11 <= calo_out_11_hwPt_V_s_fu_2724_p3;
    ap_return_12 <= calo_out_12_hwPt_V_s_fu_2744_p3;
    ap_return_13 <= calo_out_13_hwPt_V_s_fu_2764_p3;
    ap_return_14 <= calo_out_14_hwPt_V_s_fu_2784_p3;
    ap_return_15 <= calo_out_15_hwPt_V_s_fu_2804_p3;
    ap_return_16 <= calo_out_16_hwPt_V_s_fu_2824_p3;
    ap_return_17 <= calo_out_17_hwPt_V_s_fu_2844_p3;
    ap_return_18 <= calo_out_18_hwPt_V_s_fu_2864_p3;
    ap_return_19 <= calo_out_19_hwPt_V_s_fu_2884_p3;
    ap_return_2 <= calo_out_2_hwPt_V_w_fu_2551_p3;
    ap_return_20 <= calo_out_0_hwEta_V_s_fu_2504_p3;
    ap_return_21 <= calo_out_1_hwEta_V_s_fu_2524_p3;
    ap_return_22 <= calo_out_2_hwEta_V_s_fu_2544_p3;
    ap_return_23 <= calo_out_3_hwEta_V_s_fu_2564_p3;
    ap_return_24 <= calo_out_4_hwEta_V_s_fu_2590_p3;
    ap_return_25 <= calo_out_5_hwEta_V_s_fu_2610_p3;
    ap_return_26 <= calo_out_6_hwEta_V_s_fu_2630_p3;
    ap_return_27 <= calo_out_7_hwEta_V_s_fu_2650_p3;
    ap_return_28 <= calo_out_8_hwEta_V_s_fu_2670_p3;
    ap_return_29 <= calo_out_9_hwEta_V_s_fu_2690_p3;
    ap_return_3 <= calo_out_3_hwPt_V_w_fu_2571_p3;
    ap_return_30 <= calo_out_10_hwEta_V_fu_2710_p3;
    ap_return_31 <= calo_out_11_hwEta_V_fu_2730_p3;
    ap_return_32 <= calo_out_12_hwEta_V_fu_2750_p3;
    ap_return_33 <= calo_out_13_hwEta_V_fu_2770_p3;
    ap_return_34 <= calo_out_14_hwEta_V_fu_2790_p3;
    ap_return_35 <= calo_out_15_hwEta_V_fu_2810_p3;
    ap_return_36 <= calo_out_16_hwEta_V_fu_2830_p3;
    ap_return_37 <= calo_out_17_hwEta_V_fu_2850_p3;
    ap_return_38 <= calo_out_18_hwEta_V_fu_2870_p3;
    ap_return_39 <= calo_out_19_hwEta_V_fu_2890_p3;
    ap_return_4 <= calo_out_4_hwPt_V_w_fu_2584_p3;
    ap_return_40 <= calo_out_0_hwPhi_V_s_fu_2517_p3;
    ap_return_41 <= calo_out_1_hwPhi_V_s_fu_2537_p3;
    ap_return_42 <= calo_out_2_hwPhi_V_s_fu_2557_p3;
    ap_return_43 <= calo_out_3_hwPhi_V_s_fu_2577_p3;
    ap_return_44 <= calo_out_4_hwPhi_V_s_fu_2597_p3;
    ap_return_45 <= calo_out_5_hwPhi_V_s_fu_2617_p3;
    ap_return_46 <= calo_out_6_hwPhi_V_s_fu_2637_p3;
    ap_return_47 <= calo_out_7_hwPhi_V_s_fu_2657_p3;
    ap_return_48 <= calo_out_8_hwPhi_V_s_fu_2677_p3;
    ap_return_49 <= calo_out_9_hwPhi_V_s_fu_2697_p3;
    ap_return_5 <= calo_out_5_hwPt_V_w_fu_2604_p3;
    ap_return_50 <= calo_out_10_hwPhi_V_fu_2717_p3;
    ap_return_51 <= calo_out_11_hwPhi_V_fu_2737_p3;
    ap_return_52 <= calo_out_12_hwPhi_V_fu_2757_p3;
    ap_return_53 <= calo_out_13_hwPhi_V_fu_2777_p3;
    ap_return_54 <= calo_out_14_hwPhi_V_fu_2797_p3;
    ap_return_55 <= calo_out_15_hwPhi_V_fu_2817_p3;
    ap_return_56 <= calo_out_16_hwPhi_V_fu_2837_p3;
    ap_return_57 <= calo_out_17_hwPhi_V_fu_2857_p3;
    ap_return_58 <= calo_out_18_hwPhi_V_fu_2877_p3;
    ap_return_59 <= calo_out_19_hwPhi_V_fu_2897_p3;
    ap_return_6 <= calo_out_6_hwPt_V_w_fu_2624_p3;
    ap_return_7 <= calo_out_7_hwPt_V_w_fu_2644_p3;
    ap_return_8 <= calo_out_8_hwPt_V_w_fu_2664_p3;
    ap_return_9 <= calo_out_9_hwPt_V_w_fu_2684_p3;
    calo_out_0_hwEta_V_s_fu_2504_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_reg_3269(0) = '1') else 
        ap_port_reg_calo_0_hwEta_V_read;
    calo_out_0_hwPhi_V_s_fu_2517_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_reg_3269(0) = '1') else 
        ap_port_reg_calo_0_hwPhi_V_read;
    calo_out_0_hwPt_V_w_fu_2511_p3 <= 
        ap_const_lv16_0 when (sel_tmp3_reg_3269(0) = '1') else 
        ptsub_V_reg_3264;
    calo_out_10_hwEta_V_fu_2710_p3 <= 
        ap_const_lv10_0 when (sel_tmp153_reg_3389(0) = '1') else 
        ap_port_reg_calo_10_hwEta_V_rea;
    calo_out_10_hwPhi_V_fu_2717_p3 <= 
        ap_const_lv10_0 when (sel_tmp153_reg_3389(0) = '1') else 
        ap_port_reg_calo_10_hwPhi_V_rea;
    calo_out_10_hwPt_V_s_fu_2704_p3 <= 
        ap_const_lv16_0 when (sel_tmp153_reg_3389(0) = '1') else 
        ptsub_V_s_reg_3384;
    calo_out_11_hwEta_V_fu_2730_p3 <= 
        ap_const_lv10_0 when (sel_tmp168_reg_3401(0) = '1') else 
        ap_port_reg_calo_11_hwEta_V_rea;
    calo_out_11_hwPhi_V_fu_2737_p3 <= 
        ap_const_lv10_0 when (sel_tmp168_reg_3401(0) = '1') else 
        ap_port_reg_calo_11_hwPhi_V_rea;
    calo_out_11_hwPt_V_s_fu_2724_p3 <= 
        ap_const_lv16_0 when (sel_tmp168_reg_3401(0) = '1') else 
        ptsub_V_10_reg_3396;
    calo_out_12_hwEta_V_fu_2750_p3 <= 
        ap_const_lv10_0 when (sel_tmp183_reg_3413(0) = '1') else 
        ap_port_reg_calo_12_hwEta_V_rea;
    calo_out_12_hwPhi_V_fu_2757_p3 <= 
        ap_const_lv10_0 when (sel_tmp183_reg_3413(0) = '1') else 
        ap_port_reg_calo_12_hwPhi_V_rea;
    calo_out_12_hwPt_V_s_fu_2744_p3 <= 
        ap_const_lv16_0 when (sel_tmp183_reg_3413(0) = '1') else 
        ptsub_V_11_reg_3408;
    calo_out_13_hwEta_V_fu_2770_p3 <= 
        ap_const_lv10_0 when (sel_tmp198_reg_3425(0) = '1') else 
        ap_port_reg_calo_13_hwEta_V_rea;
    calo_out_13_hwPhi_V_fu_2777_p3 <= 
        ap_const_lv10_0 when (sel_tmp198_reg_3425(0) = '1') else 
        ap_port_reg_calo_13_hwPhi_V_rea;
    calo_out_13_hwPt_V_s_fu_2764_p3 <= 
        ap_const_lv16_0 when (sel_tmp198_reg_3425(0) = '1') else 
        ptsub_V_12_reg_3420;
    calo_out_14_hwEta_V_fu_2790_p3 <= 
        ap_const_lv10_0 when (sel_tmp213_reg_3437(0) = '1') else 
        ap_port_reg_calo_14_hwEta_V_rea;
    calo_out_14_hwPhi_V_fu_2797_p3 <= 
        ap_const_lv10_0 when (sel_tmp213_reg_3437(0) = '1') else 
        ap_port_reg_calo_14_hwPhi_V_rea;
    calo_out_14_hwPt_V_s_fu_2784_p3 <= 
        ap_const_lv16_0 when (sel_tmp213_reg_3437(0) = '1') else 
        ptsub_V_13_reg_3432;
    calo_out_15_hwEta_V_fu_2810_p3 <= 
        ap_const_lv10_0 when (sel_tmp228_reg_3449(0) = '1') else 
        ap_port_reg_calo_15_hwEta_V_rea;
    calo_out_15_hwPhi_V_fu_2817_p3 <= 
        ap_const_lv10_0 when (sel_tmp228_reg_3449(0) = '1') else 
        ap_port_reg_calo_15_hwPhi_V_rea;
    calo_out_15_hwPt_V_s_fu_2804_p3 <= 
        ap_const_lv16_0 when (sel_tmp228_reg_3449(0) = '1') else 
        ptsub_V_14_reg_3444;
    calo_out_16_hwEta_V_fu_2830_p3 <= 
        ap_const_lv10_0 when (sel_tmp243_reg_3461(0) = '1') else 
        ap_port_reg_calo_16_hwEta_V_rea;
    calo_out_16_hwPhi_V_fu_2837_p3 <= 
        ap_const_lv10_0 when (sel_tmp243_reg_3461(0) = '1') else 
        ap_port_reg_calo_16_hwPhi_V_rea;
    calo_out_16_hwPt_V_s_fu_2824_p3 <= 
        ap_const_lv16_0 when (sel_tmp243_reg_3461(0) = '1') else 
        ptsub_V_15_reg_3456;
    calo_out_17_hwEta_V_fu_2850_p3 <= 
        ap_const_lv10_0 when (sel_tmp258_reg_3473(0) = '1') else 
        ap_port_reg_calo_17_hwEta_V_rea;
    calo_out_17_hwPhi_V_fu_2857_p3 <= 
        ap_const_lv10_0 when (sel_tmp258_reg_3473(0) = '1') else 
        ap_port_reg_calo_17_hwPhi_V_rea;
    calo_out_17_hwPt_V_s_fu_2844_p3 <= 
        ap_const_lv16_0 when (sel_tmp258_reg_3473(0) = '1') else 
        ptsub_V_16_reg_3468;
    calo_out_18_hwEta_V_fu_2870_p3 <= 
        ap_const_lv10_0 when (sel_tmp273_reg_3485(0) = '1') else 
        ap_port_reg_calo_18_hwEta_V_rea;
    calo_out_18_hwPhi_V_fu_2877_p3 <= 
        ap_const_lv10_0 when (sel_tmp273_reg_3485(0) = '1') else 
        ap_port_reg_calo_18_hwPhi_V_rea;
    calo_out_18_hwPt_V_s_fu_2864_p3 <= 
        ap_const_lv16_0 when (sel_tmp273_reg_3485(0) = '1') else 
        ptsub_V_17_reg_3480;
    calo_out_19_hwEta_V_fu_2890_p3 <= 
        ap_const_lv10_0 when (sel_tmp288_reg_3497(0) = '1') else 
        ap_port_reg_calo_19_hwEta_V_rea;
    calo_out_19_hwPhi_V_fu_2897_p3 <= 
        ap_const_lv10_0 when (sel_tmp288_reg_3497(0) = '1') else 
        ap_port_reg_calo_19_hwPhi_V_rea;
    calo_out_19_hwPt_V_s_fu_2884_p3 <= 
        ap_const_lv16_0 when (sel_tmp288_reg_3497(0) = '1') else 
        ptsub_V_18_reg_3492;
    calo_out_1_hwEta_V_s_fu_2524_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_reg_3281(0) = '1') else 
        ap_port_reg_calo_1_hwEta_V_read;
    calo_out_1_hwPhi_V_s_fu_2537_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_reg_3281(0) = '1') else 
        ap_port_reg_calo_1_hwPhi_V_read;
    calo_out_1_hwPt_V_w_fu_2531_p3 <= 
        ap_const_lv16_0 when (sel_tmp18_reg_3281(0) = '1') else 
        ptsub_V_1_reg_3276;
    calo_out_2_hwEta_V_s_fu_2544_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_reg_3293(0) = '1') else 
        ap_port_reg_calo_2_hwEta_V_read;
    calo_out_2_hwPhi_V_s_fu_2557_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_reg_3293(0) = '1') else 
        ap_port_reg_calo_2_hwPhi_V_read;
    calo_out_2_hwPt_V_w_fu_2551_p3 <= 
        ap_const_lv16_0 when (sel_tmp33_reg_3293(0) = '1') else 
        ptsub_V_2_reg_3288;
    calo_out_3_hwEta_V_s_fu_2564_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_reg_3305(0) = '1') else 
        ap_port_reg_calo_3_hwEta_V_read;
    calo_out_3_hwPhi_V_s_fu_2577_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_reg_3305(0) = '1') else 
        ap_port_reg_calo_3_hwPhi_V_read;
    calo_out_3_hwPt_V_w_fu_2571_p3 <= 
        ap_const_lv16_0 when (sel_tmp48_reg_3305(0) = '1') else 
        ptsub_V_3_reg_3300;
    calo_out_4_hwEta_V_s_fu_2590_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_reg_3317(0) = '1') else 
        ap_port_reg_calo_4_hwEta_V_read;
    calo_out_4_hwPhi_V_s_fu_2597_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_reg_3317(0) = '1') else 
        ap_port_reg_calo_4_hwPhi_V_read;
    calo_out_4_hwPt_V_w_fu_2584_p3 <= 
        ap_const_lv16_0 when (sel_tmp63_reg_3317(0) = '1') else 
        ptsub_V_4_reg_3312;
    calo_out_5_hwEta_V_s_fu_2610_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_reg_3329(0) = '1') else 
        ap_port_reg_calo_5_hwEta_V_read;
    calo_out_5_hwPhi_V_s_fu_2617_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_reg_3329(0) = '1') else 
        ap_port_reg_calo_5_hwPhi_V_read;
    calo_out_5_hwPt_V_w_fu_2604_p3 <= 
        ap_const_lv16_0 when (sel_tmp78_reg_3329(0) = '1') else 
        ptsub_V_5_reg_3324;
    calo_out_6_hwEta_V_s_fu_2630_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_reg_3341(0) = '1') else 
        ap_port_reg_calo_6_hwEta_V_read;
    calo_out_6_hwPhi_V_s_fu_2637_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_reg_3341(0) = '1') else 
        ap_port_reg_calo_6_hwPhi_V_read;
    calo_out_6_hwPt_V_w_fu_2624_p3 <= 
        ap_const_lv16_0 when (sel_tmp93_reg_3341(0) = '1') else 
        ptsub_V_6_reg_3336;
    calo_out_7_hwEta_V_s_fu_2650_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_reg_3353(0) = '1') else 
        ap_port_reg_calo_7_hwEta_V_read;
    calo_out_7_hwPhi_V_s_fu_2657_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_reg_3353(0) = '1') else 
        ap_port_reg_calo_7_hwPhi_V_read;
    calo_out_7_hwPt_V_w_fu_2644_p3 <= 
        ap_const_lv16_0 when (sel_tmp108_reg_3353(0) = '1') else 
        ptsub_V_7_reg_3348;
    calo_out_8_hwEta_V_s_fu_2670_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_reg_3365(0) = '1') else 
        ap_port_reg_calo_8_hwEta_V_read;
    calo_out_8_hwPhi_V_s_fu_2677_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_reg_3365(0) = '1') else 
        ap_port_reg_calo_8_hwPhi_V_read;
    calo_out_8_hwPt_V_w_fu_2664_p3 <= 
        ap_const_lv16_0 when (sel_tmp123_reg_3365(0) = '1') else 
        ptsub_V_8_reg_3360;
    calo_out_9_hwEta_V_s_fu_2690_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_reg_3377(0) = '1') else 
        ap_port_reg_calo_9_hwEta_V_read;
    calo_out_9_hwPhi_V_s_fu_2697_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_reg_3377(0) = '1') else 
        ap_port_reg_calo_9_hwPhi_V_read;
    calo_out_9_hwPt_V_w_fu_2684_p3 <= 
        ap_const_lv16_0 when (sel_tmp138_reg_3377(0) = '1') else 
        ptsub_V_9_reg_3372;
    emsub_V_10_fu_1826_p2 <= std_logic_vector(unsigned(calo_11_hwEmPt_V_re) - unsigned(sumem_11_V_read));
    emsub_V_11_fu_1902_p2 <= std_logic_vector(unsigned(calo_12_hwEmPt_V_re) - unsigned(sumem_12_V_read));
    emsub_V_12_fu_1978_p2 <= std_logic_vector(unsigned(calo_13_hwEmPt_V_re) - unsigned(sumem_13_V_read));
    emsub_V_13_fu_2054_p2 <= std_logic_vector(unsigned(calo_14_hwEmPt_V_re) - unsigned(sumem_14_V_read));
    emsub_V_14_fu_2130_p2 <= std_logic_vector(unsigned(calo_15_hwEmPt_V_re) - unsigned(sumem_15_V_read));
    emsub_V_15_fu_2206_p2 <= std_logic_vector(unsigned(calo_16_hwEmPt_V_re) - unsigned(sumem_16_V_read));
    emsub_V_16_fu_2282_p2 <= std_logic_vector(unsigned(calo_17_hwEmPt_V_re) - unsigned(sumem_17_V_read));
    emsub_V_17_fu_2358_p2 <= std_logic_vector(unsigned(calo_18_hwEmPt_V_re) - unsigned(sumem_18_V_read));
    emsub_V_18_fu_2434_p2 <= std_logic_vector(unsigned(calo_19_hwEmPt_V_re) - unsigned(sumem_19_V_read));
    emsub_V_1_fu_1750_p2 <= std_logic_vector(unsigned(calo_10_hwEmPt_V_re) - unsigned(sumem_10_V_read));
    emsub_V_2_fu_1142_p2 <= std_logic_vector(unsigned(calo_2_hwEmPt_V_rea) - unsigned(sumem_2_V_read));
    emsub_V_3_fu_1218_p2 <= std_logic_vector(unsigned(calo_3_hwEmPt_V_rea) - unsigned(sumem_3_V_read));
    emsub_V_4_fu_1294_p2 <= std_logic_vector(unsigned(calo_4_hwEmPt_V_rea) - unsigned(sumem_4_V_read));
    emsub_V_5_fu_1370_p2 <= std_logic_vector(unsigned(calo_5_hwEmPt_V_rea) - unsigned(sumem_5_V_read));
    emsub_V_6_fu_1446_p2 <= std_logic_vector(unsigned(calo_6_hwEmPt_V_rea) - unsigned(sumem_6_V_read));
    emsub_V_7_fu_1522_p2 <= std_logic_vector(unsigned(calo_7_hwEmPt_V_rea) - unsigned(sumem_7_V_read));
    emsub_V_8_fu_1598_p2 <= std_logic_vector(unsigned(calo_8_hwEmPt_V_rea) - unsigned(sumem_8_V_read));
    emsub_V_9_fu_1674_p2 <= std_logic_vector(unsigned(calo_9_hwEmPt_V_rea) - unsigned(sumem_9_V_read));
    emsub_V_fu_990_p2 <= std_logic_vector(unsigned(calo_0_hwEmPt_V_rea) - unsigned(sumem_0_V_read));
    emsub_V_s_fu_1066_p2 <= std_logic_vector(unsigned(calo_1_hwEmPt_V_rea) - unsigned(sumem_1_V_read));
    ptsub_V_10_fu_1820_p2 <= std_logic_vector(unsigned(calo_11_hwPt_V_read) - unsigned(sumem_11_V_read));
    ptsub_V_11_fu_1896_p2 <= std_logic_vector(unsigned(calo_12_hwPt_V_read) - unsigned(sumem_12_V_read));
    ptsub_V_12_fu_1972_p2 <= std_logic_vector(unsigned(calo_13_hwPt_V_read) - unsigned(sumem_13_V_read));
    ptsub_V_13_fu_2048_p2 <= std_logic_vector(unsigned(calo_14_hwPt_V_read) - unsigned(sumem_14_V_read));
    ptsub_V_14_fu_2124_p2 <= std_logic_vector(unsigned(calo_15_hwPt_V_read) - unsigned(sumem_15_V_read));
    ptsub_V_15_fu_2200_p2 <= std_logic_vector(unsigned(calo_16_hwPt_V_read) - unsigned(sumem_16_V_read));
    ptsub_V_16_fu_2276_p2 <= std_logic_vector(unsigned(calo_17_hwPt_V_read) - unsigned(sumem_17_V_read));
    ptsub_V_17_fu_2352_p2 <= std_logic_vector(unsigned(calo_18_hwPt_V_read) - unsigned(sumem_18_V_read));
    ptsub_V_18_fu_2428_p2 <= std_logic_vector(unsigned(calo_19_hwPt_V_read) - unsigned(sumem_19_V_read));
    ptsub_V_1_fu_1060_p2 <= std_logic_vector(unsigned(calo_1_hwPt_V_read) - unsigned(sumem_1_V_read));
    ptsub_V_2_fu_1136_p2 <= std_logic_vector(unsigned(calo_2_hwPt_V_read) - unsigned(sumem_2_V_read));
    ptsub_V_3_fu_1212_p2 <= std_logic_vector(unsigned(calo_3_hwPt_V_read) - unsigned(sumem_3_V_read));
    ptsub_V_4_fu_1288_p2 <= std_logic_vector(unsigned(calo_4_hwPt_V_read) - unsigned(sumem_4_V_read));
    ptsub_V_5_fu_1364_p2 <= std_logic_vector(unsigned(calo_5_hwPt_V_read) - unsigned(sumem_5_V_read));
    ptsub_V_6_fu_1440_p2 <= std_logic_vector(unsigned(calo_6_hwPt_V_read) - unsigned(sumem_6_V_read));
    ptsub_V_7_fu_1516_p2 <= std_logic_vector(unsigned(calo_7_hwPt_V_read) - unsigned(sumem_7_V_read));
    ptsub_V_8_fu_1592_p2 <= std_logic_vector(unsigned(calo_8_hwPt_V_read) - unsigned(sumem_8_V_read));
    ptsub_V_9_fu_1668_p2 <= std_logic_vector(unsigned(calo_9_hwPt_V_read) - unsigned(sumem_9_V_read));
    ptsub_V_fu_984_p2 <= std_logic_vector(unsigned(calo_0_hwPt_V_read) - unsigned(sumem_0_V_read));
    ptsub_V_s_fu_1744_p2 <= std_logic_vector(unsigned(calo_10_hwPt_V_read) - unsigned(sumem_10_V_read));
        r_V_10_fu_1766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_157_fu_1756_p4),16));

        r_V_11_fu_1842_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_159_fu_1832_p4),16));

        r_V_12_fu_1918_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_161_fu_1908_p4),16));

        r_V_13_fu_1994_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_163_fu_1984_p4),16));

        r_V_14_fu_2070_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_165_fu_2060_p4),16));

        r_V_15_fu_2146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_167_fu_2136_p4),16));

        r_V_16_fu_2222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_169_fu_2212_p4),16));

        r_V_17_fu_2298_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_171_fu_2288_p4),16));

        r_V_18_fu_2374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_173_fu_2364_p4),16));

        r_V_19_fu_2450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_175_fu_2440_p4),16));

        r_V_1_fu_1082_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_139_fu_1072_p4),16));

        r_V_2_fu_1158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_141_fu_1148_p4),16));

        r_V_3_fu_1234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_143_fu_1224_p4),16));

        r_V_4_fu_1310_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_145_fu_1300_p4),16));

        r_V_5_fu_1386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_147_fu_1376_p4),16));

        r_V_6_fu_1462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_149_fu_1452_p4),16));

        r_V_7_fu_1538_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_151_fu_1528_p4),16));

        r_V_8_fu_1614_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_153_fu_1604_p4),16));

        r_V_9_10_fu_1856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_160_fu_1846_p4),16));

        r_V_9_11_fu_1932_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_162_fu_1922_p4),16));

        r_V_9_12_fu_2008_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_164_fu_1998_p4),16));

        r_V_9_13_fu_2084_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_166_fu_2074_p4),16));

        r_V_9_14_fu_2160_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_168_fu_2150_p4),16));

        r_V_9_15_fu_2236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_170_fu_2226_p4),16));

        r_V_9_16_fu_2312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_172_fu_2302_p4),16));

        r_V_9_17_fu_2388_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_174_fu_2378_p4),16));

        r_V_9_18_fu_2464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_176_fu_2454_p4),16));

        r_V_9_1_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_140_fu_1086_p4),16));

        r_V_9_2_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_142_fu_1162_p4),16));

        r_V_9_3_fu_1248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_144_fu_1238_p4),16));

        r_V_9_4_fu_1324_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_146_fu_1314_p4),16));

        r_V_9_5_fu_1400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_148_fu_1390_p4),16));

        r_V_9_6_fu_1476_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_150_fu_1466_p4),16));

        r_V_9_7_fu_1552_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_152_fu_1542_p4),16));

        r_V_9_8_fu_1628_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_154_fu_1618_p4),16));

        r_V_9_9_fu_1704_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_156_fu_1694_p4),16));

        r_V_9_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_138_fu_1010_p4),16));

        r_V_9_s_fu_1780_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_158_fu_1770_p4),16));

        r_V_fu_1006_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_996_p4),16));

        r_V_s_fu_1690_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_155_fu_1680_p4),16));

    rev56_fu_1042_p2 <= (slt56_fu_1036_p2 xor ap_const_lv1_1);
    rev57_fu_1106_p2 <= (slt57_fu_1100_p2 xor ap_const_lv1_1);
    rev58_fu_1118_p2 <= (slt58_fu_1112_p2 xor ap_const_lv1_1);
    rev59_fu_1182_p2 <= (slt59_fu_1176_p2 xor ap_const_lv1_1);
    rev60_fu_1194_p2 <= (slt60_fu_1188_p2 xor ap_const_lv1_1);
    rev61_fu_1258_p2 <= (slt61_fu_1252_p2 xor ap_const_lv1_1);
    rev62_fu_1270_p2 <= (slt62_fu_1264_p2 xor ap_const_lv1_1);
    rev63_fu_1334_p2 <= (slt63_fu_1328_p2 xor ap_const_lv1_1);
    rev64_fu_1346_p2 <= (slt64_fu_1340_p2 xor ap_const_lv1_1);
    rev65_fu_1410_p2 <= (slt65_fu_1404_p2 xor ap_const_lv1_1);
    rev66_fu_1422_p2 <= (slt66_fu_1416_p2 xor ap_const_lv1_1);
    rev67_fu_1486_p2 <= (slt67_fu_1480_p2 xor ap_const_lv1_1);
    rev68_fu_1498_p2 <= (slt68_fu_1492_p2 xor ap_const_lv1_1);
    rev69_fu_1562_p2 <= (slt69_fu_1556_p2 xor ap_const_lv1_1);
    rev70_fu_1574_p2 <= (slt70_fu_1568_p2 xor ap_const_lv1_1);
    rev71_fu_1638_p2 <= (slt71_fu_1632_p2 xor ap_const_lv1_1);
    rev72_fu_1650_p2 <= (slt72_fu_1644_p2 xor ap_const_lv1_1);
    rev73_fu_1714_p2 <= (slt73_fu_1708_p2 xor ap_const_lv1_1);
    rev74_fu_1726_p2 <= (slt74_fu_1720_p2 xor ap_const_lv1_1);
    rev75_fu_1790_p2 <= (slt75_fu_1784_p2 xor ap_const_lv1_1);
    rev76_fu_1802_p2 <= (slt76_fu_1796_p2 xor ap_const_lv1_1);
    rev77_fu_1866_p2 <= (slt77_fu_1860_p2 xor ap_const_lv1_1);
    rev78_fu_1878_p2 <= (slt78_fu_1872_p2 xor ap_const_lv1_1);
    rev79_fu_1942_p2 <= (slt79_fu_1936_p2 xor ap_const_lv1_1);
    rev80_fu_1954_p2 <= (slt80_fu_1948_p2 xor ap_const_lv1_1);
    rev81_fu_2018_p2 <= (slt81_fu_2012_p2 xor ap_const_lv1_1);
    rev82_fu_2030_p2 <= (slt82_fu_2024_p2 xor ap_const_lv1_1);
    rev83_fu_2094_p2 <= (slt83_fu_2088_p2 xor ap_const_lv1_1);
    rev84_fu_2106_p2 <= (slt84_fu_2100_p2 xor ap_const_lv1_1);
    rev85_fu_2170_p2 <= (slt85_fu_2164_p2 xor ap_const_lv1_1);
    rev86_fu_2182_p2 <= (slt86_fu_2176_p2 xor ap_const_lv1_1);
    rev87_fu_2246_p2 <= (slt87_fu_2240_p2 xor ap_const_lv1_1);
    rev88_fu_2258_p2 <= (slt88_fu_2252_p2 xor ap_const_lv1_1);
    rev89_fu_2322_p2 <= (slt89_fu_2316_p2 xor ap_const_lv1_1);
    rev90_fu_2334_p2 <= (slt90_fu_2328_p2 xor ap_const_lv1_1);
    rev91_fu_2398_p2 <= (slt91_fu_2392_p2 xor ap_const_lv1_1);
    rev92_fu_2410_p2 <= (slt92_fu_2404_p2 xor ap_const_lv1_1);
    rev93_fu_2474_p2 <= (slt93_fu_2468_p2 xor ap_const_lv1_1);
    rev94_fu_2486_p2 <= (slt94_fu_2480_p2 xor ap_const_lv1_1);
    rev_fu_1030_p2 <= (slt_fu_1024_p2 xor ap_const_lv1_1);
    sel_tmp107_fu_1580_p1 <= (0=>calo_7_hwIsEM_read, others=>'-');
    sel_tmp107_fu_1580_p2 <= (sel_tmp107_fu_1580_p1 and rev70_fu_1574_p2);
    sel_tmp108_fu_1586_p2 <= (sel_tmp107_fu_1580_p2 or rev69_fu_1562_p2);
    sel_tmp122_fu_1656_p1 <= (0=>calo_8_hwIsEM_read, others=>'-');
    sel_tmp122_fu_1656_p2 <= (sel_tmp122_fu_1656_p1 and rev72_fu_1650_p2);
    sel_tmp123_fu_1662_p2 <= (sel_tmp122_fu_1656_p2 or rev71_fu_1638_p2);
    sel_tmp137_fu_1732_p1 <= (0=>calo_9_hwIsEM_read, others=>'-');
    sel_tmp137_fu_1732_p2 <= (sel_tmp137_fu_1732_p1 and rev74_fu_1726_p2);
    sel_tmp138_fu_1738_p2 <= (sel_tmp137_fu_1732_p2 or rev73_fu_1714_p2);
    sel_tmp152_fu_1808_p1 <= (0=>calo_10_hwIsEM_read, others=>'-');
    sel_tmp152_fu_1808_p2 <= (sel_tmp152_fu_1808_p1 and rev76_fu_1802_p2);
    sel_tmp153_fu_1814_p2 <= (sel_tmp152_fu_1808_p2 or rev75_fu_1790_p2);
    sel_tmp167_fu_1884_p1 <= (0=>calo_11_hwIsEM_read, others=>'-');
    sel_tmp167_fu_1884_p2 <= (sel_tmp167_fu_1884_p1 and rev78_fu_1878_p2);
    sel_tmp168_fu_1890_p2 <= (sel_tmp167_fu_1884_p2 or rev77_fu_1866_p2);
    sel_tmp17_fu_1124_p1 <= (0=>calo_1_hwIsEM_read, others=>'-');
    sel_tmp17_fu_1124_p2 <= (sel_tmp17_fu_1124_p1 and rev58_fu_1118_p2);
    sel_tmp182_fu_1960_p1 <= (0=>calo_12_hwIsEM_read, others=>'-');
    sel_tmp182_fu_1960_p2 <= (sel_tmp182_fu_1960_p1 and rev80_fu_1954_p2);
    sel_tmp183_fu_1966_p2 <= (sel_tmp182_fu_1960_p2 or rev79_fu_1942_p2);
    sel_tmp18_fu_1130_p2 <= (sel_tmp17_fu_1124_p2 or rev57_fu_1106_p2);
    sel_tmp197_fu_2036_p1 <= (0=>calo_13_hwIsEM_read, others=>'-');
    sel_tmp197_fu_2036_p2 <= (sel_tmp197_fu_2036_p1 and rev82_fu_2030_p2);
    sel_tmp198_fu_2042_p2 <= (sel_tmp197_fu_2036_p2 or rev81_fu_2018_p2);
    sel_tmp212_fu_2112_p1 <= (0=>calo_14_hwIsEM_read, others=>'-');
    sel_tmp212_fu_2112_p2 <= (sel_tmp212_fu_2112_p1 and rev84_fu_2106_p2);
    sel_tmp213_fu_2118_p2 <= (sel_tmp212_fu_2112_p2 or rev83_fu_2094_p2);
    sel_tmp227_fu_2188_p1 <= (0=>calo_15_hwIsEM_read, others=>'-');
    sel_tmp227_fu_2188_p2 <= (sel_tmp227_fu_2188_p1 and rev86_fu_2182_p2);
    sel_tmp228_fu_2194_p2 <= (sel_tmp227_fu_2188_p2 or rev85_fu_2170_p2);
    sel_tmp242_fu_2264_p1 <= (0=>calo_16_hwIsEM_read, others=>'-');
    sel_tmp242_fu_2264_p2 <= (sel_tmp242_fu_2264_p1 and rev88_fu_2258_p2);
    sel_tmp243_fu_2270_p2 <= (sel_tmp242_fu_2264_p2 or rev87_fu_2246_p2);
    sel_tmp257_fu_2340_p1 <= (0=>calo_17_hwIsEM_read, others=>'-');
    sel_tmp257_fu_2340_p2 <= (sel_tmp257_fu_2340_p1 and rev90_fu_2334_p2);
    sel_tmp258_fu_2346_p2 <= (sel_tmp257_fu_2340_p2 or rev89_fu_2322_p2);
    sel_tmp272_fu_2416_p1 <= (0=>calo_18_hwIsEM_read, others=>'-');
    sel_tmp272_fu_2416_p2 <= (sel_tmp272_fu_2416_p1 and rev92_fu_2410_p2);
    sel_tmp273_fu_2422_p2 <= (sel_tmp272_fu_2416_p2 or rev91_fu_2398_p2);
    sel_tmp287_fu_2492_p1 <= (0=>calo_19_hwIsEM_read, others=>'-');
    sel_tmp287_fu_2492_p2 <= (sel_tmp287_fu_2492_p1 and rev94_fu_2486_p2);
    sel_tmp288_fu_2498_p2 <= (sel_tmp287_fu_2492_p2 or rev93_fu_2474_p2);
    sel_tmp2_fu_1048_p1 <= (0=>calo_0_hwIsEM_read, others=>'-');
    sel_tmp2_fu_1048_p2 <= (sel_tmp2_fu_1048_p1 and rev56_fu_1042_p2);
    sel_tmp32_fu_1200_p1 <= (0=>calo_2_hwIsEM_read, others=>'-');
    sel_tmp32_fu_1200_p2 <= (sel_tmp32_fu_1200_p1 and rev60_fu_1194_p2);
    sel_tmp33_fu_1206_p2 <= (sel_tmp32_fu_1200_p2 or rev59_fu_1182_p2);
    sel_tmp3_fu_1054_p2 <= (sel_tmp2_fu_1048_p2 or rev_fu_1030_p2);
    sel_tmp47_fu_1276_p1 <= (0=>calo_3_hwIsEM_read, others=>'-');
    sel_tmp47_fu_1276_p2 <= (sel_tmp47_fu_1276_p1 and rev62_fu_1270_p2);
    sel_tmp48_fu_1282_p2 <= (sel_tmp47_fu_1276_p2 or rev61_fu_1258_p2);
    sel_tmp62_fu_1352_p1 <= (0=>calo_4_hwIsEM_read, others=>'-');
    sel_tmp62_fu_1352_p2 <= (sel_tmp62_fu_1352_p1 and rev64_fu_1346_p2);
    sel_tmp63_fu_1358_p2 <= (sel_tmp62_fu_1352_p2 or rev63_fu_1334_p2);
    sel_tmp77_fu_1428_p1 <= (0=>calo_5_hwIsEM_read, others=>'-');
    sel_tmp77_fu_1428_p2 <= (sel_tmp77_fu_1428_p1 and rev66_fu_1422_p2);
    sel_tmp78_fu_1434_p2 <= (sel_tmp77_fu_1428_p2 or rev65_fu_1410_p2);
    sel_tmp92_fu_1504_p1 <= (0=>calo_6_hwIsEM_read, others=>'-');
    sel_tmp92_fu_1504_p2 <= (sel_tmp92_fu_1504_p1 and rev68_fu_1498_p2);
    sel_tmp93_fu_1510_p2 <= (sel_tmp92_fu_1504_p2 or rev67_fu_1486_p2);
    slt56_fu_1036_p2 <= "1" when (signed(r_V_9_fu_1020_p1) < signed(emsub_V_fu_990_p2)) else "0";
    slt57_fu_1100_p2 <= "1" when (signed(r_V_1_fu_1082_p1) < signed(ptsub_V_1_fu_1060_p2)) else "0";
    slt58_fu_1112_p2 <= "1" when (signed(r_V_9_1_fu_1096_p1) < signed(emsub_V_s_fu_1066_p2)) else "0";
    slt59_fu_1176_p2 <= "1" when (signed(r_V_2_fu_1158_p1) < signed(ptsub_V_2_fu_1136_p2)) else "0";
    slt60_fu_1188_p2 <= "1" when (signed(r_V_9_2_fu_1172_p1) < signed(emsub_V_2_fu_1142_p2)) else "0";
    slt61_fu_1252_p2 <= "1" when (signed(r_V_3_fu_1234_p1) < signed(ptsub_V_3_fu_1212_p2)) else "0";
    slt62_fu_1264_p2 <= "1" when (signed(r_V_9_3_fu_1248_p1) < signed(emsub_V_3_fu_1218_p2)) else "0";
    slt63_fu_1328_p2 <= "1" when (signed(r_V_4_fu_1310_p1) < signed(ptsub_V_4_fu_1288_p2)) else "0";
    slt64_fu_1340_p2 <= "1" when (signed(r_V_9_4_fu_1324_p1) < signed(emsub_V_4_fu_1294_p2)) else "0";
    slt65_fu_1404_p2 <= "1" when (signed(r_V_5_fu_1386_p1) < signed(ptsub_V_5_fu_1364_p2)) else "0";
    slt66_fu_1416_p2 <= "1" when (signed(r_V_9_5_fu_1400_p1) < signed(emsub_V_5_fu_1370_p2)) else "0";
    slt67_fu_1480_p2 <= "1" when (signed(r_V_6_fu_1462_p1) < signed(ptsub_V_6_fu_1440_p2)) else "0";
    slt68_fu_1492_p2 <= "1" when (signed(r_V_9_6_fu_1476_p1) < signed(emsub_V_6_fu_1446_p2)) else "0";
    slt69_fu_1556_p2 <= "1" when (signed(r_V_7_fu_1538_p1) < signed(ptsub_V_7_fu_1516_p2)) else "0";
    slt70_fu_1568_p2 <= "1" when (signed(r_V_9_7_fu_1552_p1) < signed(emsub_V_7_fu_1522_p2)) else "0";
    slt71_fu_1632_p2 <= "1" when (signed(r_V_8_fu_1614_p1) < signed(ptsub_V_8_fu_1592_p2)) else "0";
    slt72_fu_1644_p2 <= "1" when (signed(r_V_9_8_fu_1628_p1) < signed(emsub_V_8_fu_1598_p2)) else "0";
    slt73_fu_1708_p2 <= "1" when (signed(r_V_s_fu_1690_p1) < signed(ptsub_V_9_fu_1668_p2)) else "0";
    slt74_fu_1720_p2 <= "1" when (signed(r_V_9_9_fu_1704_p1) < signed(emsub_V_9_fu_1674_p2)) else "0";
    slt75_fu_1784_p2 <= "1" when (signed(r_V_10_fu_1766_p1) < signed(ptsub_V_s_fu_1744_p2)) else "0";
    slt76_fu_1796_p2 <= "1" when (signed(r_V_9_s_fu_1780_p1) < signed(emsub_V_1_fu_1750_p2)) else "0";
    slt77_fu_1860_p2 <= "1" when (signed(r_V_11_fu_1842_p1) < signed(ptsub_V_10_fu_1820_p2)) else "0";
    slt78_fu_1872_p2 <= "1" when (signed(r_V_9_10_fu_1856_p1) < signed(emsub_V_10_fu_1826_p2)) else "0";
    slt79_fu_1936_p2 <= "1" when (signed(r_V_12_fu_1918_p1) < signed(ptsub_V_11_fu_1896_p2)) else "0";
    slt80_fu_1948_p2 <= "1" when (signed(r_V_9_11_fu_1932_p1) < signed(emsub_V_11_fu_1902_p2)) else "0";
    slt81_fu_2012_p2 <= "1" when (signed(r_V_13_fu_1994_p1) < signed(ptsub_V_12_fu_1972_p2)) else "0";
    slt82_fu_2024_p2 <= "1" when (signed(r_V_9_12_fu_2008_p1) < signed(emsub_V_12_fu_1978_p2)) else "0";
    slt83_fu_2088_p2 <= "1" when (signed(r_V_14_fu_2070_p1) < signed(ptsub_V_13_fu_2048_p2)) else "0";
    slt84_fu_2100_p2 <= "1" when (signed(r_V_9_13_fu_2084_p1) < signed(emsub_V_13_fu_2054_p2)) else "0";
    slt85_fu_2164_p2 <= "1" when (signed(r_V_15_fu_2146_p1) < signed(ptsub_V_14_fu_2124_p2)) else "0";
    slt86_fu_2176_p2 <= "1" when (signed(r_V_9_14_fu_2160_p1) < signed(emsub_V_14_fu_2130_p2)) else "0";
    slt87_fu_2240_p2 <= "1" when (signed(r_V_16_fu_2222_p1) < signed(ptsub_V_15_fu_2200_p2)) else "0";
    slt88_fu_2252_p2 <= "1" when (signed(r_V_9_15_fu_2236_p1) < signed(emsub_V_15_fu_2206_p2)) else "0";
    slt89_fu_2316_p2 <= "1" when (signed(r_V_17_fu_2298_p1) < signed(ptsub_V_16_fu_2276_p2)) else "0";
    slt90_fu_2328_p2 <= "1" when (signed(r_V_9_16_fu_2312_p1) < signed(emsub_V_16_fu_2282_p2)) else "0";
    slt91_fu_2392_p2 <= "1" when (signed(r_V_18_fu_2374_p1) < signed(ptsub_V_17_fu_2352_p2)) else "0";
    slt92_fu_2404_p2 <= "1" when (signed(r_V_9_17_fu_2388_p1) < signed(emsub_V_17_fu_2358_p2)) else "0";
    slt93_fu_2468_p2 <= "1" when (signed(r_V_19_fu_2450_p1) < signed(ptsub_V_18_fu_2428_p2)) else "0";
    slt94_fu_2480_p2 <= "1" when (signed(r_V_9_18_fu_2464_p1) < signed(emsub_V_18_fu_2434_p2)) else "0";
    slt_fu_1024_p2 <= "1" when (signed(r_V_fu_1006_p1) < signed(ptsub_V_fu_984_p2)) else "0";
    tmp_138_fu_1010_p4 <= calo_0_hwEmPt_V_rea(15 downto 3);
    tmp_139_fu_1072_p4 <= calo_1_hwPt_V_read(15 downto 4);
    tmp_140_fu_1086_p4 <= calo_1_hwEmPt_V_rea(15 downto 3);
    tmp_141_fu_1148_p4 <= calo_2_hwPt_V_read(15 downto 4);
    tmp_142_fu_1162_p4 <= calo_2_hwEmPt_V_rea(15 downto 3);
    tmp_143_fu_1224_p4 <= calo_3_hwPt_V_read(15 downto 4);
    tmp_144_fu_1238_p4 <= calo_3_hwEmPt_V_rea(15 downto 3);
    tmp_145_fu_1300_p4 <= calo_4_hwPt_V_read(15 downto 4);
    tmp_146_fu_1314_p4 <= calo_4_hwEmPt_V_rea(15 downto 3);
    tmp_147_fu_1376_p4 <= calo_5_hwPt_V_read(15 downto 4);
    tmp_148_fu_1390_p4 <= calo_5_hwEmPt_V_rea(15 downto 3);
    tmp_149_fu_1452_p4 <= calo_6_hwPt_V_read(15 downto 4);
    tmp_150_fu_1466_p4 <= calo_6_hwEmPt_V_rea(15 downto 3);
    tmp_151_fu_1528_p4 <= calo_7_hwPt_V_read(15 downto 4);
    tmp_152_fu_1542_p4 <= calo_7_hwEmPt_V_rea(15 downto 3);
    tmp_153_fu_1604_p4 <= calo_8_hwPt_V_read(15 downto 4);
    tmp_154_fu_1618_p4 <= calo_8_hwEmPt_V_rea(15 downto 3);
    tmp_155_fu_1680_p4 <= calo_9_hwPt_V_read(15 downto 4);
    tmp_156_fu_1694_p4 <= calo_9_hwEmPt_V_rea(15 downto 3);
    tmp_157_fu_1756_p4 <= calo_10_hwPt_V_read(15 downto 4);
    tmp_158_fu_1770_p4 <= calo_10_hwEmPt_V_re(15 downto 3);
    tmp_159_fu_1832_p4 <= calo_11_hwPt_V_read(15 downto 4);
    tmp_160_fu_1846_p4 <= calo_11_hwEmPt_V_re(15 downto 3);
    tmp_161_fu_1908_p4 <= calo_12_hwPt_V_read(15 downto 4);
    tmp_162_fu_1922_p4 <= calo_12_hwEmPt_V_re(15 downto 3);
    tmp_163_fu_1984_p4 <= calo_13_hwPt_V_read(15 downto 4);
    tmp_164_fu_1998_p4 <= calo_13_hwEmPt_V_re(15 downto 3);
    tmp_165_fu_2060_p4 <= calo_14_hwPt_V_read(15 downto 4);
    tmp_166_fu_2074_p4 <= calo_14_hwEmPt_V_re(15 downto 3);
    tmp_167_fu_2136_p4 <= calo_15_hwPt_V_read(15 downto 4);
    tmp_168_fu_2150_p4 <= calo_15_hwEmPt_V_re(15 downto 3);
    tmp_169_fu_2212_p4 <= calo_16_hwPt_V_read(15 downto 4);
    tmp_170_fu_2226_p4 <= calo_16_hwEmPt_V_re(15 downto 3);
    tmp_171_fu_2288_p4 <= calo_17_hwPt_V_read(15 downto 4);
    tmp_172_fu_2302_p4 <= calo_17_hwEmPt_V_re(15 downto 3);
    tmp_173_fu_2364_p4 <= calo_18_hwPt_V_read(15 downto 4);
    tmp_174_fu_2378_p4 <= calo_18_hwEmPt_V_re(15 downto 3);
    tmp_175_fu_2440_p4 <= calo_19_hwPt_V_read(15 downto 4);
    tmp_176_fu_2454_p4 <= calo_19_hwEmPt_V_re(15 downto 3);
    tmp_s_fu_996_p4 <= calo_0_hwPt_V_read(15 downto 4);
end behav;
