
-- ==============================================================
--
-- RTL generated by C++ written by rrivera at fnal dot gov
-- May 2019
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

use work.regionizer_pkg.all;
use work.algo_pkg.all;

entity algo_wrapper is
	port (
		clk         	: in std_logic;

		valid_in    	: in std_logic;
		objects_in  	: in raw_physics_object_arr_t(ALGO_INPUT_OBJECTS_COUNT-1 downto 0); --ALGO_INPUT_OBJECTS_COUNT constant defined in regionizer_pkg
		vertex      	: in std_logic_vector(VERTEX_BIT_WIDTH-1 downto 0);

		valid_out   	: out std_logic;
		results_out 	: out raw_algo_object_out_arr_t(ALGO_OBJECTS_OUT-1 downto 0);      --ALGO_OBJECTS_OUT constant defined in algo_pkg

		reset       	: in std_logic
	);


end entity algo_wrapper;




architecture behav of algo_wrapper is


	component mp7wrapped_pfalgo3_full is 
		port ( 

			input_0_V 	 : in  std_logic_vector(31 downto 0);
			input_1_V 	 : in  std_logic_vector(31 downto 0);
			input_2_V 	 : in  std_logic_vector(31 downto 0);
			input_3_V 	 : in  std_logic_vector(31 downto 0);
			input_4_V 	 : in  std_logic_vector(31 downto 0);
			input_5_V 	 : in  std_logic_vector(31 downto 0);
			input_6_V 	 : in  std_logic_vector(31 downto 0);
			input_7_V 	 : in  std_logic_vector(31 downto 0);
			input_8_V 	 : in  std_logic_vector(31 downto 0);
			input_9_V 	 : in  std_logic_vector(31 downto 0);
			input_10_V 	 : in  std_logic_vector(31 downto 0);
			input_11_V 	 : in  std_logic_vector(31 downto 0);
			input_12_V 	 : in  std_logic_vector(31 downto 0);
			input_13_V 	 : in  std_logic_vector(31 downto 0);
			input_14_V 	 : in  std_logic_vector(31 downto 0);
			input_15_V 	 : in  std_logic_vector(31 downto 0);
			input_16_V 	 : in  std_logic_vector(31 downto 0);
			input_17_V 	 : in  std_logic_vector(31 downto 0);
			input_18_V 	 : in  std_logic_vector(31 downto 0);
			input_19_V 	 : in  std_logic_vector(31 downto 0);
			input_20_V 	 : in  std_logic_vector(31 downto 0);
			input_21_V 	 : in  std_logic_vector(31 downto 0);
			input_22_V 	 : in  std_logic_vector(31 downto 0);
			input_23_V 	 : in  std_logic_vector(31 downto 0);
			input_24_V 	 : in  std_logic_vector(31 downto 0);
			input_25_V 	 : in  std_logic_vector(31 downto 0);
			input_26_V 	 : in  std_logic_vector(31 downto 0);
			input_27_V 	 : in  std_logic_vector(31 downto 0);
			input_28_V 	 : in  std_logic_vector(31 downto 0);
			input_29_V 	 : in  std_logic_vector(31 downto 0);
			input_30_V 	 : in  std_logic_vector(31 downto 0);
			input_31_V 	 : in  std_logic_vector(31 downto 0);
			input_32_V 	 : in  std_logic_vector(31 downto 0);
			input_33_V 	 : in  std_logic_vector(31 downto 0);
			input_34_V 	 : in  std_logic_vector(31 downto 0);
			input_35_V 	 : in  std_logic_vector(31 downto 0);
			input_36_V 	 : in  std_logic_vector(31 downto 0);
			input_37_V 	 : in  std_logic_vector(31 downto 0);
			input_38_V 	 : in  std_logic_vector(31 downto 0);
			input_39_V 	 : in  std_logic_vector(31 downto 0);
			input_40_V 	 : in  std_logic_vector(31 downto 0);
			input_41_V 	 : in  std_logic_vector(31 downto 0);
			input_42_V 	 : in  std_logic_vector(31 downto 0);
			input_43_V 	 : in  std_logic_vector(31 downto 0);
			input_44_V 	 : in  std_logic_vector(31 downto 0);
			input_45_V 	 : in  std_logic_vector(31 downto 0);
			input_46_V 	 : in  std_logic_vector(31 downto 0);
			input_47_V 	 : in  std_logic_vector(31 downto 0);
			input_48_V 	 : in  std_logic_vector(31 downto 0);
			input_49_V 	 : in  std_logic_vector(31 downto 0);
			input_50_V 	 : in  std_logic_vector(31 downto 0);
			input_51_V 	 : in  std_logic_vector(31 downto 0);
			input_52_V 	 : in  std_logic_vector(31 downto 0);
			input_53_V 	 : in  std_logic_vector(31 downto 0);
			input_54_V 	 : in  std_logic_vector(31 downto 0);
			input_55_V 	 : in  std_logic_vector(31 downto 0);
			input_56_V 	 : in  std_logic_vector(31 downto 0);
			input_57_V 	 : in  std_logic_vector(31 downto 0);
			input_58_V 	 : in  std_logic_vector(31 downto 0);
			input_59_V 	 : in  std_logic_vector(31 downto 0);
			input_60_V 	 : in  std_logic_vector(31 downto 0);
			input_61_V 	 : in  std_logic_vector(31 downto 0);
			input_62_V 	 : in  std_logic_vector(31 downto 0);
			input_63_V 	 : in  std_logic_vector(31 downto 0);
			input_64_V 	 : in  std_logic_vector(31 downto 0);
			input_65_V 	 : in  std_logic_vector(31 downto 0);
			input_66_V 	 : in  std_logic_vector(31 downto 0);
			input_67_V 	 : in  std_logic_vector(31 downto 0);
			input_68_V 	 : in  std_logic_vector(31 downto 0);
			input_69_V 	 : in  std_logic_vector(31 downto 0);
			input_70_V 	 : in  std_logic_vector(31 downto 0);
			input_71_V 	 : in  std_logic_vector(31 downto 0);
			input_72_V 	 : in  std_logic_vector(31 downto 0);
			input_73_V 	 : in  std_logic_vector(31 downto 0);
			input_74_V 	 : in  std_logic_vector(31 downto 0);
			input_75_V 	 : in  std_logic_vector(31 downto 0);
			input_76_V 	 : in  std_logic_vector(31 downto 0);
			input_77_V 	 : in  std_logic_vector(31 downto 0);
			input_78_V 	 : in  std_logic_vector(31 downto 0);
			input_79_V 	 : in  std_logic_vector(31 downto 0);
			input_80_V 	 : in  std_logic_vector(31 downto 0);
			input_81_V 	 : in  std_logic_vector(31 downto 0);
			input_82_V 	 : in  std_logic_vector(31 downto 0);
			input_83_V 	 : in  std_logic_vector(31 downto 0);
			input_84_V 	 : in  std_logic_vector(31 downto 0);
			input_85_V 	 : in  std_logic_vector(31 downto 0);
			input_86_V 	 : in  std_logic_vector(31 downto 0);
			input_87_V 	 : in  std_logic_vector(31 downto 0);
			input_88_V 	 : in  std_logic_vector(31 downto 0);
			input_89_V 	 : in  std_logic_vector(31 downto 0);
			input_90_V 	 : in  std_logic_vector(31 downto 0);
			input_91_V 	 : in  std_logic_vector(31 downto 0);
			input_92_V 	 : in  std_logic_vector(31 downto 0);
			input_93_V 	 : in  std_logic_vector(31 downto 0);
			input_94_V 	 : in  std_logic_vector(31 downto 0);
			input_95_V 	 : in  std_logic_vector(31 downto 0);
			input_96_V 	 : in  std_logic_vector(31 downto 0);
			input_97_V 	 : in  std_logic_vector(31 downto 0);
			input_98_V 	 : in  std_logic_vector(31 downto 0);
			input_99_V 	 : in  std_logic_vector(31 downto 0);
			input_100_V 	 : in  std_logic_vector(31 downto 0);
			input_101_V 	 : in  std_logic_vector(31 downto 0);
			input_102_V 	 : in  std_logic_vector(31 downto 0);
			input_103_V 	 : in  std_logic_vector(31 downto 0);
			input_104_V 	 : in  std_logic_vector(31 downto 0);
			input_105_V 	 : in  std_logic_vector(31 downto 0);
			input_106_V 	 : in  std_logic_vector(31 downto 0);
			input_107_V 	 : in  std_logic_vector(31 downto 0);
			input_108_V 	 : in  std_logic_vector(31 downto 0);
			input_109_V 	 : in  std_logic_vector(31 downto 0);
			input_110_V 	 : in  std_logic_vector(31 downto 0);
			input_111_V 	 : in  std_logic_vector(31 downto 0);
			input_112_V 	 : in  std_logic_vector(31 downto 0);
			input_113_V 	 : in  std_logic_vector(31 downto 0);
			input_114_V 	 : in  std_logic_vector(31 downto 0);
			input_115_V 	 : in  std_logic_vector(31 downto 0);
			input_116_V 	 : in  std_logic_vector(31 downto 0);
			input_117_V 	 : in  std_logic_vector(31 downto 0);
			input_118_V 	 : in  std_logic_vector(31 downto 0);
			input_119_V 	 : in  std_logic_vector(31 downto 0);
			input_120_V 	 : in  std_logic_vector(31 downto 0);
			input_121_V 	 : in  std_logic_vector(31 downto 0);
			input_122_V 	 : in  std_logic_vector(31 downto 0);
			input_123_V 	 : in  std_logic_vector(31 downto 0);
			output_0_V 	 : out std_logic_vector(31 downto 0);
			output_1_V 	 : out std_logic_vector(31 downto 0);
			output_2_V 	 : out std_logic_vector(31 downto 0);
			output_3_V 	 : out std_logic_vector(31 downto 0);
			output_4_V 	 : out std_logic_vector(31 downto 0);
			output_5_V 	 : out std_logic_vector(31 downto 0);
			output_6_V 	 : out std_logic_vector(31 downto 0);
			output_7_V 	 : out std_logic_vector(31 downto 0);
			output_8_V 	 : out std_logic_vector(31 downto 0);
			output_9_V 	 : out std_logic_vector(31 downto 0);
			output_10_V 	 : out std_logic_vector(31 downto 0);
			output_11_V 	 : out std_logic_vector(31 downto 0);
			output_12_V 	 : out std_logic_vector(31 downto 0);
			output_13_V 	 : out std_logic_vector(31 downto 0);
			output_14_V 	 : out std_logic_vector(31 downto 0);
			output_15_V 	 : out std_logic_vector(31 downto 0);
			output_16_V 	 : out std_logic_vector(31 downto 0);
			output_17_V 	 : out std_logic_vector(31 downto 0);
			output_18_V 	 : out std_logic_vector(31 downto 0);
			output_19_V 	 : out std_logic_vector(31 downto 0);
			output_20_V 	 : out std_logic_vector(31 downto 0);
			output_21_V 	 : out std_logic_vector(31 downto 0);
			output_22_V 	 : out std_logic_vector(31 downto 0);
			output_23_V 	 : out std_logic_vector(31 downto 0);
			output_24_V 	 : out std_logic_vector(31 downto 0);
			output_25_V 	 : out std_logic_vector(31 downto 0);
			output_26_V 	 : out std_logic_vector(31 downto 0);
			output_27_V 	 : out std_logic_vector(31 downto 0);
			output_28_V 	 : out std_logic_vector(31 downto 0);
			output_29_V 	 : out std_logic_vector(31 downto 0);
			output_30_V 	 : out std_logic_vector(31 downto 0);
			output_31_V 	 : out std_logic_vector(31 downto 0);
			output_32_V 	 : out std_logic_vector(31 downto 0);
			output_33_V 	 : out std_logic_vector(31 downto 0);
			output_34_V 	 : out std_logic_vector(31 downto 0);
			output_35_V 	 : out std_logic_vector(31 downto 0);
			output_36_V 	 : out std_logic_vector(31 downto 0);
			output_37_V 	 : out std_logic_vector(31 downto 0);
			output_38_V 	 : out std_logic_vector(31 downto 0);
			output_39_V 	 : out std_logic_vector(31 downto 0);
			output_40_V 	 : out std_logic_vector(31 downto 0);
			output_41_V 	 : out std_logic_vector(31 downto 0);
			output_42_V 	 : out std_logic_vector(31 downto 0);
			output_43_V 	 : out std_logic_vector(31 downto 0);
			output_44_V 	 : out std_logic_vector(31 downto 0);
			output_45_V 	 : out std_logic_vector(31 downto 0);
			output_46_V 	 : out std_logic_vector(31 downto 0);
			output_47_V 	 : out std_logic_vector(31 downto 0);
			output_48_V 	 : out std_logic_vector(31 downto 0);
			output_49_V 	 : out std_logic_vector(31 downto 0);
			output_50_V 	 : out std_logic_vector(31 downto 0);
			output_51_V 	 : out std_logic_vector(31 downto 0);
			output_52_V 	 : out std_logic_vector(31 downto 0);
			output_53_V 	 : out std_logic_vector(31 downto 0);
			output_54_V 	 : out std_logic_vector(31 downto 0);
			output_55_V 	 : out std_logic_vector(31 downto 0);
			output_56_V 	 : out std_logic_vector(31 downto 0);
			output_57_V 	 : out std_logic_vector(31 downto 0);
			output_58_V 	 : out std_logic_vector(31 downto 0);
			output_59_V 	 : out std_logic_vector(31 downto 0);
			output_60_V 	 : out std_logic_vector(31 downto 0);
			output_61_V 	 : out std_logic_vector(31 downto 0);
			output_62_V 	 : out std_logic_vector(31 downto 0);
			output_63_V 	 : out std_logic_vector(31 downto 0);
			output_64_V 	 : out std_logic_vector(31 downto 0);
			output_65_V 	 : out std_logic_vector(31 downto 0);
			output_66_V 	 : out std_logic_vector(31 downto 0);
			output_67_V 	 : out std_logic_vector(31 downto 0);
			output_68_V 	 : out std_logic_vector(31 downto 0);
			output_69_V 	 : out std_logic_vector(31 downto 0);
			output_70_V 	 : out std_logic_vector(31 downto 0);
			output_71_V 	 : out std_logic_vector(31 downto 0);
			output_72_V 	 : out std_logic_vector(31 downto 0);
			output_73_V 	 : out std_logic_vector(31 downto 0);
			output_74_V 	 : out std_logic_vector(31 downto 0);
			output_75_V 	 : out std_logic_vector(31 downto 0);
			output_76_V 	 : out std_logic_vector(31 downto 0);
			output_77_V 	 : out std_logic_vector(31 downto 0);
			output_78_V 	 : out std_logic_vector(31 downto 0);
			output_79_V 	 : out std_logic_vector(31 downto 0);
			output_80_V 	 : out std_logic_vector(31 downto 0);
			output_81_V 	 : out std_logic_vector(31 downto 0);
			output_82_V 	 : out std_logic_vector(31 downto 0);
			output_83_V 	 : out std_logic_vector(31 downto 0);
			output_84_V 	 : out std_logic_vector(31 downto 0);
			output_85_V 	 : out std_logic_vector(31 downto 0);
			output_86_V 	 : out std_logic_vector(31 downto 0);
			output_87_V 	 : out std_logic_vector(31 downto 0);
			output_88_V 	 : out std_logic_vector(31 downto 0);
			output_89_V 	 : out std_logic_vector(31 downto 0);
			output_90_V 	 : out std_logic_vector(31 downto 0);
			output_91_V 	 : out std_logic_vector(31 downto 0);
			output_92_V 	 : out std_logic_vector(31 downto 0);
			output_93_V 	 : out std_logic_vector(31 downto 0);
			output_94_V 	 : out std_logic_vector(31 downto 0);
			output_95_V 	 : out std_logic_vector(31 downto 0);
			output_96_V 	 : out std_logic_vector(31 downto 0);
			output_97_V 	 : out std_logic_vector(31 downto 0);
			output_98_V 	 : out std_logic_vector(31 downto 0);
			output_99_V 	 : out std_logic_vector(31 downto 0);
			output_100_V 	 : out std_logic_vector(31 downto 0);
			output_101_V 	 : out std_logic_vector(31 downto 0);
			output_102_V 	 : out std_logic_vector(31 downto 0);
			output_103_V 	 : out std_logic_vector(31 downto 0);
			output_104_V 	 : out std_logic_vector(31 downto 0);
			output_105_V 	 : out std_logic_vector(31 downto 0);
			output_106_V 	 : out std_logic_vector(31 downto 0);
			output_107_V 	 : out std_logic_vector(31 downto 0);
			output_108_V 	 : out std_logic_vector(31 downto 0);
			output_109_V 	 : out std_logic_vector(31 downto 0);
			output_110_V 	 : out std_logic_vector(31 downto 0);
			output_111_V 	 : out std_logic_vector(31 downto 0);
			output_112_V 	 : out std_logic_vector(31 downto 0);
			output_113_V 	 : out std_logic_vector(31 downto 0);

			Z0_V     	 : in  std_logic_vector(VERTEX_BIT_WIDTH-1 downto 0);

			ap_clk   	 : in  std_logic;
			ap_rst   	 : in  std_logic;
			ap_start 	 : in  std_logic;
			ap_done  	 : out std_logic;
			ap_idle  	 : out std_logic;
			ap_ready 	 : out std_logic
	);
	end component mp7wrapped_pfalgo3_full;


	signal algo_objects_out : raw_algo_object_out_arr_t(ALGO_OBJECTS_OUT-1 downto 0);

begin


	results_out <= algo_objects_out;




	algo_instance : mp7wrapped_pfalgo3_full
		port map (
			input_0_V 	 => objects_in(0)(31 downto 0),
			input_1_V 	 => objects_in(0)(63 downto 32),
			input_2_V 	 => objects_in(1)(31 downto 0),
			input_3_V 	 => objects_in(1)(63 downto 32),
			input_4_V 	 => objects_in(2)(31 downto 0),
			input_5_V 	 => objects_in(2)(63 downto 32),
			input_6_V 	 => objects_in(3)(31 downto 0),
			input_7_V 	 => objects_in(3)(63 downto 32),
			input_8_V 	 => objects_in(4)(31 downto 0),
			input_9_V 	 => objects_in(4)(63 downto 32),
			input_10_V 	 => objects_in(5)(31 downto 0),
			input_11_V 	 => objects_in(5)(63 downto 32),
			input_12_V 	 => objects_in(6)(31 downto 0),
			input_13_V 	 => objects_in(6)(63 downto 32),
			input_14_V 	 => objects_in(7)(31 downto 0),
			input_15_V 	 => objects_in(7)(63 downto 32),
			input_16_V 	 => objects_in(8)(31 downto 0),
			input_17_V 	 => objects_in(8)(63 downto 32),
			input_18_V 	 => objects_in(9)(31 downto 0),
			input_19_V 	 => objects_in(9)(63 downto 32),
			input_20_V 	 => objects_in(10)(31 downto 0),
			input_21_V 	 => objects_in(10)(63 downto 32),
			input_22_V 	 => objects_in(11)(31 downto 0),
			input_23_V 	 => objects_in(11)(63 downto 32),
			input_24_V 	 => objects_in(12)(31 downto 0),
			input_25_V 	 => objects_in(12)(63 downto 32),
			input_26_V 	 => objects_in(13)(31 downto 0),
			input_27_V 	 => objects_in(13)(63 downto 32),
			input_28_V 	 => objects_in(14)(31 downto 0),
			input_29_V 	 => objects_in(14)(63 downto 32),
			input_30_V 	 => objects_in(15)(31 downto 0),
			input_31_V 	 => objects_in(15)(63 downto 32),
			input_32_V 	 => objects_in(16)(31 downto 0),
			input_33_V 	 => objects_in(16)(63 downto 32),
			input_34_V 	 => objects_in(17)(31 downto 0),
			input_35_V 	 => objects_in(17)(63 downto 32),
			input_36_V 	 => objects_in(18)(31 downto 0),
			input_37_V 	 => objects_in(18)(63 downto 32),
			input_38_V 	 => objects_in(19)(31 downto 0),
			input_39_V 	 => objects_in(19)(63 downto 32),
			input_40_V 	 => objects_in(20)(31 downto 0),
			input_41_V 	 => objects_in(20)(63 downto 32),
			input_42_V 	 => objects_in(21)(31 downto 0),
			input_43_V 	 => objects_in(21)(63 downto 32),
			input_44_V 	 => objects_in(22)(31 downto 0),
			input_45_V 	 => objects_in(22)(63 downto 32),
			input_46_V 	 => objects_in(23)(31 downto 0),
			input_47_V 	 => objects_in(23)(63 downto 32),
			input_48_V 	 => objects_in(24)(31 downto 0),
			input_49_V 	 => objects_in(24)(63 downto 32),
			input_50_V 	 => objects_in(25)(31 downto 0),
			input_51_V 	 => objects_in(25)(63 downto 32),
			input_52_V 	 => objects_in(26)(31 downto 0),
			input_53_V 	 => objects_in(26)(63 downto 32),
			input_54_V 	 => objects_in(27)(31 downto 0),
			input_55_V 	 => objects_in(27)(63 downto 32),
			input_56_V 	 => objects_in(28)(31 downto 0),
			input_57_V 	 => objects_in(28)(63 downto 32),
			input_58_V 	 => objects_in(29)(31 downto 0),
			input_59_V 	 => objects_in(29)(63 downto 32),
			input_60_V 	 => objects_in(30)(31 downto 0),
			input_61_V 	 => objects_in(30)(63 downto 32),
			input_62_V 	 => objects_in(31)(31 downto 0),
			input_63_V 	 => objects_in(31)(63 downto 32),
			input_64_V 	 => objects_in(32)(31 downto 0),
			input_65_V 	 => objects_in(32)(63 downto 32),
			input_66_V 	 => objects_in(33)(31 downto 0),
			input_67_V 	 => objects_in(33)(63 downto 32),
			input_68_V 	 => objects_in(34)(31 downto 0),
			input_69_V 	 => objects_in(34)(63 downto 32),
			input_70_V 	 => objects_in(35)(31 downto 0),
			input_71_V 	 => objects_in(35)(63 downto 32),
			input_72_V 	 => objects_in(36)(31 downto 0),
			input_73_V 	 => objects_in(36)(63 downto 32),
			input_74_V 	 => objects_in(37)(31 downto 0),
			input_75_V 	 => objects_in(37)(63 downto 32),
			input_76_V 	 => objects_in(38)(31 downto 0),
			input_77_V 	 => objects_in(38)(63 downto 32),
			input_78_V 	 => objects_in(39)(31 downto 0),
			input_79_V 	 => objects_in(39)(63 downto 32),
			input_80_V 	 => objects_in(40)(31 downto 0),
			input_81_V 	 => objects_in(40)(63 downto 32),
			input_82_V 	 => objects_in(41)(31 downto 0),
			input_83_V 	 => objects_in(41)(63 downto 32),
			input_84_V 	 => objects_in(42)(31 downto 0),
			input_85_V 	 => objects_in(42)(63 downto 32),
			input_86_V 	 => objects_in(43)(31 downto 0),
			input_87_V 	 => objects_in(43)(63 downto 32),
			input_88_V 	 => objects_in(44)(31 downto 0),
			input_89_V 	 => objects_in(44)(63 downto 32),
			input_90_V 	 => objects_in(45)(31 downto 0),
			input_91_V 	 => objects_in(45)(63 downto 32),
			input_92_V 	 => objects_in(46)(31 downto 0),
			input_93_V 	 => objects_in(46)(63 downto 32),
			input_94_V 	 => objects_in(47)(31 downto 0),
			input_95_V 	 => objects_in(47)(63 downto 32),
			input_96_V 	 => objects_in(48)(31 downto 0),
			input_97_V 	 => objects_in(48)(63 downto 32),
			input_98_V 	 => objects_in(49)(31 downto 0),
			input_99_V 	 => objects_in(49)(63 downto 32),
			input_100_V 	 => objects_in(50)(31 downto 0),
			input_101_V 	 => objects_in(50)(63 downto 32),
			input_102_V 	 => objects_in(51)(31 downto 0),
			input_103_V 	 => objects_in(51)(63 downto 32),
			input_104_V 	 => objects_in(52)(31 downto 0),
			input_105_V 	 => objects_in(52)(63 downto 32),
			input_106_V 	 => objects_in(53)(31 downto 0),
			input_107_V 	 => objects_in(53)(63 downto 32),
			input_108_V 	 => objects_in(54)(31 downto 0),
			input_109_V 	 => objects_in(54)(63 downto 32),
			input_110_V 	 => objects_in(55)(31 downto 0),
			input_111_V 	 => objects_in(55)(63 downto 32),
			input_112_V 	 => objects_in(56)(31 downto 0),
			input_113_V 	 => objects_in(56)(63 downto 32),
			input_114_V 	 => objects_in(57)(31 downto 0),
			input_115_V 	 => objects_in(57)(63 downto 32),
			input_116_V 	 => objects_in(58)(31 downto 0),
			input_117_V 	 => objects_in(58)(63 downto 32),
			input_118_V 	 => objects_in(59)(31 downto 0),
			input_119_V 	 => objects_in(59)(63 downto 32),
			input_120_V 	 => null_raw_algo_object_in,
			input_121_V 	 => null_raw_algo_object_in,
			input_122_V 	 => null_raw_algo_object_in,
			input_123_V 	 => null_raw_algo_object_in,
			output_0_V 	 => algo_objects_out(0)(31 downto 0),
			output_1_V 	 => algo_objects_out(0)(63 downto 32),
			output_2_V 	 => algo_objects_out(1)(31 downto 0),
			output_3_V 	 => algo_objects_out(1)(63 downto 32),
			output_4_V 	 => algo_objects_out(2)(31 downto 0),
			output_5_V 	 => algo_objects_out(2)(63 downto 32),
			output_6_V 	 => algo_objects_out(3)(31 downto 0),
			output_7_V 	 => algo_objects_out(3)(63 downto 32),
			output_8_V 	 => algo_objects_out(4)(31 downto 0),
			output_9_V 	 => algo_objects_out(4)(63 downto 32),
			output_10_V 	 => algo_objects_out(5)(31 downto 0),
			output_11_V 	 => algo_objects_out(5)(63 downto 32),
			output_12_V 	 => algo_objects_out(6)(31 downto 0),
			output_13_V 	 => algo_objects_out(6)(63 downto 32),
			output_14_V 	 => algo_objects_out(7)(31 downto 0),
			output_15_V 	 => algo_objects_out(7)(63 downto 32),
			output_16_V 	 => algo_objects_out(8)(31 downto 0),
			output_17_V 	 => algo_objects_out(8)(63 downto 32),
			output_18_V 	 => algo_objects_out(9)(31 downto 0),
			output_19_V 	 => algo_objects_out(9)(63 downto 32),
			output_20_V 	 => algo_objects_out(10)(31 downto 0),
			output_21_V 	 => algo_objects_out(10)(63 downto 32),
			output_22_V 	 => algo_objects_out(11)(31 downto 0),
			output_23_V 	 => algo_objects_out(11)(63 downto 32),
			output_24_V 	 => algo_objects_out(12)(31 downto 0),
			output_25_V 	 => algo_objects_out(12)(63 downto 32),
			output_26_V 	 => algo_objects_out(13)(31 downto 0),
			output_27_V 	 => algo_objects_out(13)(63 downto 32),
			output_28_V 	 => algo_objects_out(14)(31 downto 0),
			output_29_V 	 => algo_objects_out(14)(63 downto 32),
			output_30_V 	 => algo_objects_out(15)(31 downto 0),
			output_31_V 	 => algo_objects_out(15)(63 downto 32),
			output_32_V 	 => algo_objects_out(16)(31 downto 0),
			output_33_V 	 => algo_objects_out(16)(63 downto 32),
			output_34_V 	 => algo_objects_out(17)(31 downto 0),
			output_35_V 	 => algo_objects_out(17)(63 downto 32),
			output_36_V 	 => algo_objects_out(18)(31 downto 0),
			output_37_V 	 => algo_objects_out(18)(63 downto 32),
			output_38_V 	 => algo_objects_out(19)(31 downto 0),
			output_39_V 	 => algo_objects_out(19)(63 downto 32),
			output_40_V 	 => algo_objects_out(20)(31 downto 0),
			output_41_V 	 => algo_objects_out(20)(63 downto 32),
			output_42_V 	 => algo_objects_out(21)(31 downto 0),
			output_43_V 	 => algo_objects_out(21)(63 downto 32),
			output_44_V 	 => algo_objects_out(22)(31 downto 0),
			output_45_V 	 => algo_objects_out(22)(63 downto 32),
			output_46_V 	 => algo_objects_out(23)(31 downto 0),
			output_47_V 	 => algo_objects_out(23)(63 downto 32),
			output_48_V 	 => algo_objects_out(24)(31 downto 0),
			output_49_V 	 => algo_objects_out(24)(63 downto 32),
			output_50_V 	 => algo_objects_out(25)(31 downto 0),
			output_51_V 	 => algo_objects_out(25)(63 downto 32),
			output_52_V 	 => algo_objects_out(26)(31 downto 0),
			output_53_V 	 => algo_objects_out(26)(63 downto 32),
			output_54_V 	 => algo_objects_out(27)(31 downto 0),
			output_55_V 	 => algo_objects_out(27)(63 downto 32),
			output_56_V 	 => algo_objects_out(28)(31 downto 0),
			output_57_V 	 => algo_objects_out(28)(63 downto 32),
			output_58_V 	 => algo_objects_out(29)(31 downto 0),
			output_59_V 	 => algo_objects_out(29)(63 downto 32),
			output_60_V 	 => algo_objects_out(30)(31 downto 0),
			output_61_V 	 => algo_objects_out(30)(63 downto 32),
			output_62_V 	 => algo_objects_out(31)(31 downto 0),
			output_63_V 	 => algo_objects_out(31)(63 downto 32),
			output_64_V 	 => algo_objects_out(32)(31 downto 0),
			output_65_V 	 => algo_objects_out(32)(63 downto 32),
			output_66_V 	 => algo_objects_out(33)(31 downto 0),
			output_67_V 	 => algo_objects_out(33)(63 downto 32),
			output_68_V 	 => algo_objects_out(34)(31 downto 0),
			output_69_V 	 => algo_objects_out(34)(63 downto 32),
			output_70_V 	 => algo_objects_out(35)(31 downto 0),
			output_71_V 	 => algo_objects_out(35)(63 downto 32),
			output_72_V 	 => algo_objects_out(36)(31 downto 0),
			output_73_V 	 => algo_objects_out(36)(63 downto 32),
			output_74_V 	 => algo_objects_out(37)(31 downto 0),
			output_75_V 	 => algo_objects_out(37)(63 downto 32),
			output_76_V 	 => algo_objects_out(38)(31 downto 0),
			output_77_V 	 => algo_objects_out(38)(63 downto 32),
			output_78_V 	 => algo_objects_out(39)(31 downto 0),
			output_79_V 	 => algo_objects_out(39)(63 downto 32),
			output_80_V 	 => algo_objects_out(40)(31 downto 0),
			output_81_V 	 => algo_objects_out(40)(63 downto 32),
			output_82_V 	 => algo_objects_out(41)(31 downto 0),
			output_83_V 	 => algo_objects_out(41)(63 downto 32),
			output_84_V 	 => algo_objects_out(42)(31 downto 0),
			output_85_V 	 => algo_objects_out(42)(63 downto 32),
			output_86_V 	 => algo_objects_out(43)(31 downto 0),
			output_87_V 	 => algo_objects_out(43)(63 downto 32),
			output_88_V 	 => algo_objects_out(44)(31 downto 0),
			output_89_V 	 => algo_objects_out(44)(63 downto 32),
			output_90_V 	 => algo_objects_out(45)(31 downto 0),
			output_91_V 	 => algo_objects_out(45)(63 downto 32),
			output_92_V 	 => algo_objects_out(46)(31 downto 0),
			output_93_V 	 => algo_objects_out(46)(63 downto 32),
			output_94_V 	 => algo_objects_out(47)(31 downto 0),
			output_95_V 	 => algo_objects_out(47)(63 downto 32),
			output_96_V 	 => algo_objects_out(48)(31 downto 0),
			output_97_V 	 => algo_objects_out(48)(63 downto 32),
			output_98_V 	 => algo_objects_out(49)(31 downto 0),
			output_99_V 	 => algo_objects_out(49)(63 downto 32),
			output_100_V 	 => algo_objects_out(50)(31 downto 0),
			output_101_V 	 => algo_objects_out(50)(63 downto 32),
			output_102_V 	 => algo_objects_out(51)(31 downto 0),
			output_103_V 	 => algo_objects_out(51)(63 downto 32),
			output_104_V 	 => algo_objects_out(52)(31 downto 0),
			output_105_V 	 => algo_objects_out(52)(63 downto 32),
			output_106_V 	 => algo_objects_out(53)(31 downto 0),
			output_107_V 	 => algo_objects_out(53)(63 downto 32),
			output_108_V 	 => algo_objects_out(54)(31 downto 0),
			output_109_V 	 => algo_objects_out(54)(63 downto 32),
			output_110_V 	 => algo_objects_out(55)(31 downto 0),
			output_111_V 	 => algo_objects_out(55)(63 downto 32),
			output_112_V 	 => algo_objects_out(56)(31 downto 0),
			output_113_V 	 => algo_objects_out(56)(63 downto 32),

			Z0_V     	 => vertex,

			ap_clk   	 => clk,
			ap_rst   	 => reset,
			ap_start 	 => valid_in,
			ap_done  	 => valid_out,
			ap_idle  	 => open,
			ap_ready 	 => open
		);


end behav;
