# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu9p-flgb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.cache/wt [current_project]
set_property parent.project_path /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/algo_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/regionizer_params_pkg.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/regionizer_wrapper.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/infra_wrapper.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/level2_ram_buffers.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/level2_ram_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/level2_uram_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/level1_fifo_only_buffer.vhd
  /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/sim/level1_fifo_only_buffers.vhd
}
read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/infra_fifo/infra_fifo_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/regionizer_clocks/regionizer_clocks_ooc.xdc]

read_ip -quiet /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo.xci
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/CorrelatorTrigger/otsdaq-cms-firmware/regionizer_full/regionizer.srcs/sources_1/ip/level1_fifo/level1_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top infra_wrapper -part xcvu9p-flgb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef infra_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file infra_wrapper_utilization_synth.rpt -pb infra_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
